#!/usr/bin/env python3
"""Kazakh productive agglutinative rules + mined exceptions.

Kazakh is a Kipchak Turkic language cited here by its -у / -ю verbal-noun
infinitive (алу, беру, сөйлеу, тою). The synthetic core is generated by
rule (see produce(), mirrored EXACTLY in src/kaz.rs) from the stem — the
infinitive minus its final -у, with -ю → -й:

  * two-way vowel harmony: the low vowel A ∈ {а, е}, the high vowel
    Y ∈ {ы, і}, the plural K ∈ {қ, к} and the 2pl D-А-r ∈ {дар, дер},
    chosen by the backness of the stem's last vowel;
  * aorist / present-future: stem + а/е (+ й after an open vowel) + the
    full personal endings (мын/сың/сыз/ды/мыз/сыңдар/сыздар/ды);
  * definite past / preterite: stem + ты/ті (after a voiceless stop) or
    ды/ді + the possessive endings (м/ң/ңыз/-/қ/ңдар/ңыздар/-), with the
    stem-final voiced stop devoicing before it (б→п, г→к, ғ→қ: табу →
    таптым);
  * presumptive future: stem + ар/ер (+ р after an open vowel) + the full
    personal endings.

Everything that deviates — verbs with a hidden stem vowel the infinitive
drops (оқу ← оқы, суу ← суы, баю ← байы), monosyllable irregulars (кию,
деу-class -р futures are handled, but кию is not) and assorted lexical
oddities — is mined per feature cell into data/kaz/parts.tsv.

Single oracle (kaikki.org only): UniMorph kaz has no verb rows, so this is
a Beta engine, scored directly against kaikki like Azerbaijani.

Usage: mine.py data/kaz/kaikki.tsv > data/kaz/parts.tsv
"""
import sys
from collections import defaultdict

VOW = "аәеоөұүыіэиуёюя"
BACK = "аоұыуёя"
CONN = "аәеоөұүыіэ"      # open vowels that take the -й aorist connective
VOICELESS = "кқптсшчцфхһщ"
DEVOICE = {"б": "п", "г": "к", "ғ": "қ"}

PN = ["1;SG", "2;SG;INFM", "2;SG;FORM", "3;SG",
      "1;PL", "2;PL;INFM", "2;PL;FORM", "3;PL"]

CELLS = (
    [f"V;AOR;{p}" for p in PN]
    + [f"V;PST;{p}" for p in PN]
    + [f"V;FUT;{p}" for p in PN]
    + ["V;IMP;2;SG", "V;IMP;2;SG;FORM", "V;IMP;2;PL", "V;NFIN"]
)


def stem_of(lemma):
    if lemma.endswith("ю"):
        return lemma[:-1] + "й"
    if lemma.endswith("у"):
        return lemma[:-1]
    return None


def harmony(stem):
    v = next((c for c in reversed(stem) if c in VOW), "а")
    if v in BACK:
        return "а", "ы", "қ", "дар"
    return "е", "і", "к", "дер"


def produce(lemma, feat):
    stem = stem_of(lemma)
    if stem is None:
        return None
    if feat == "V;NFIN":
        return lemma
    A, Y, K, DAr = harmony(stem)
    last = stem[-1]
    parts = feat.split(";")
    tense = parts[1]
    pn = ";".join(parts[2:])

    if tense == "IMP":
        if pn == "2;SG":
            return stem
        base = stem + (Y if last not in VOW else "")
        if pn == "2;SG;FORM":
            return base + "ң" + Y + "з"
        if pn == "2;PL":
            return base + "ң" + DAr
        return None

    if tense == "AOR":
        if last in CONN:
            base = stem[:-1] + "и" if last in "ыі" else stem + "й"
        else:
            base = stem + A
            if last == "й" and A == "а":
                base = stem[:-1] + "я"
        end = {"1;SG": "м" + Y + "н", "2;SG;INFM": "с" + Y + "ң",
               "2;SG;FORM": "с" + Y + "з", "3;SG": "д" + Y,
               "1;PL": "м" + Y + "з", "2;PL;INFM": "с" + Y + "ң" + DAr,
               "2;PL;FORM": "с" + Y + "з" + DAr, "3;PL": "д" + Y}
        return base + end[pn]

    if tense == "PST":
        st = stem[:-1] + DEVOICE[last] if last in DEVOICE else stem
        D = "т" if st[-1] in VOICELESS else "д"
        pb = st + D + Y
        end = {"1;SG": "м", "2;SG;INFM": "ң", "2;SG;FORM": "ң" + Y + "з",
               "3;SG": "", "1;PL": K, "2;PL;INFM": "ң" + DAr,
               "2;PL;FORM": "ң" + Y + "з" + DAr, "3;PL": ""}
        return pb + end[pn]

    if tense == "FUT":
        if last in CONN:
            base = stem + "р"
        else:
            base = stem + A + "р"
            if last == "й" and A == "а":
                base = stem[:-1] + "я" + "р"
        end = {"1;SG": "м" + Y + "н", "2;SG;INFM": "с" + Y + "ң",
               "2;SG;FORM": "с" + Y + "з", "3;SG": "",
               "1;PL": "м" + Y + "з", "2;PL;INFM": "с" + Y + "ң" + DAr,
               "2;PL;FORM": "с" + Y + "з" + DAr, "3;PL": ""}
        return base + end[pn]
    return None


def main(path):
    gold = defaultdict(lambda: defaultdict(set))
    for line in open(path):
        a = line.rstrip("\n").split("\t")
        if len(a) >= 3:
            gold[a[0]][a[2]].add(a[1])

    total = hit = 0
    parts = {}
    for cit, cells in gold.items():
        if stem_of(cit) is None:
            continue
        row = {}
        for feat, forms in cells.items():
            if feat not in CELLS:
                continue
            pred = produce(cit, feat)
            if pred is None:
                continue
            total += 1
            if pred in forms:
                hit += 1
            else:
                row[feat] = sorted(forms)[0]
        if row:
            parts[cit] = row

    sys.stderr.write(
        f"rule accuracy: {hit}/{total} = {100*hit/max(total,1):.2f}%, "
        f"mined lemmas: {len(parts)}\n"
    )
    print("# lemma(infinitive)\t" + "\t".join(CELLS))
    for cit in sorted(parts):
        print(cit + "\t" + "\t".join(parts[cit].get(c, "-") for c in CELLS))


if __name__ == "__main__":
    main(sys.argv[1])
