#!/usr/bin/env python3
"""Mine the Greek exception table from the two oracle TSVs.

Greek is cited by its 1sg imperfective present. Two things are productive
and generated by rule (see productive(), mirrored in src/ell.rs): the
-ω-class imperfective present (λύν-ω/-εις/-ει/-ουμε/-ετε/-ουν) and the
active present participle / gerund (stem + -οντας). Everything else is
lexical and mined: the contracted -άω/-ώ presents, the augmented and
stress-shifted imperfect, the perfective past (aorist, whose perfective
stem is unpredictable), and the two imperatives. Where the two oracles
attest the same form we store that; otherwise the UniMorph reading.

Usage: mine.py data/ell/unimorph.tsv data/ell/kaikki.tsv > data/ell/parts.tsv
"""
import sys
from collections import defaultdict

CELLS = [
    "V;1;SG;IPFV;PRS", "V;2;SG;IPFV;PRS", "V;3;SG;IPFV;PRS",
    "V;1;PL;IPFV;PRS", "V;2;PL;IPFV;PRS", "V;3;PL;IPFV;PRS",
    "V;1;SG;IPFV;PST", "V;2;SG;IPFV;PST", "V;3;SG;IPFV;PST",
    "V;1;PL;IPFV;PST", "V;2;PL;IPFV;PST", "V;3;PL;IPFV;PST",
    "V;1;SG;PFV;PST", "V;2;SG;PFV;PST", "V;3;SG;PFV;PST",
    "V;1;PL;PFV;PST", "V;2;PL;PFV;PST", "V;3;PL;PFV;PST",
    "V;2;SG;IMP", "V;2;PL;IMP", "V;PTCP",
]

PRS = {"1;SG": "ω", "2;SG": "εις", "3;SG": "ει",
       "1;PL": "ουμε", "2;PL": "ετε", "3;PL": "ουν"}


def productive(cit, feat):
    if not cit.endswith("ω"):
        return None
    stem = cit[:-1]
    if feat == "V;PTCP":
        return stem + "οντας"
    if feat.startswith("V;") and feat.endswith(";IPFV;PRS"):
        pn = feat[2:].split(";IPFV")[0]
        return stem + PRS[pn] if pn in PRS else None
    return None


def main(uni_path, kai_path):
    def read(path):
        d = defaultdict(set)
        for l in open(path):
            a = l.rstrip("\n").split("\t")
            if len(a) >= 3 and a[2].startswith("V"):
                d[(a[0], a[2])].add(a[1])
        return d
    uni, kai = read(uni_path), read(kai_path)

    def chosen(lemma, feat):
        a, b = uni.get((lemma, feat), set()), kai.get((lemma, feat), set())
        pool = (a & b) or a or b
        return sorted(pool)[0] if pool else None

    lemmas = sorted({l for (l, f) in list(uni) + list(kai) if f == "V;1;SG;IPFV;PRS"})
    print("# lemma(1sg.ipfv.pres)\t" + "\t".join(CELLS) + '  ("-" = productive default)')
    for lemma in lemmas:
        if not lemma or " " in lemma:
            continue
        out = []
        for c in CELLS:
            f = chosen(lemma, c)
            out.append(f if f and f != productive(lemma, c) else "-")
        if any(x != "-" for x in out):
            print(lemma + "\t" + "\t".join(out))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
