#!/usr/bin/env python3
"""Mine the Albanian exception table from the two oracle TSVs.

Albanian is cited by its 1sg present indicative. The productive -oj class
(abdikoj, denominatives and loanwords — the largest and most regular
class) is generated by rule (see productive(), mirrored in src/sqi.rs):
present, imperfect, aorist, admirative present and imperfect, imperative
and participle. Every other class (consonant stems, -en/-ë verbs,
suppletives) and every irregular -oj verb is mined. Where the two oracles
attest the same form we store that; otherwise the UniMorph reading.

Usage: mine.py data/sqi/unimorph.tsv data/sqi/kaikki.tsv > data/sqi/parts.tsv
"""
import sys
from collections import defaultdict

CELLS = [
    "V;1;SG;IND;PRS", "V;2;SG;IND;PRS", "V;3;SG;IND;PRS",
    "V;1;PL;IND;PRS", "V;2;PL;IND;PRS", "V;3;PL;IND;PRS",
    "V;1;SG;IND;IPFV", "V;2;SG;IND;IPFV", "V;3;SG;IND;IPFV",
    "V;1;PL;IND;IPFV", "V;2;PL;IND;IPFV", "V;3;PL;IND;IPFV",
    "V;1;SG;IND;PST", "V;2;SG;IND;PST", "V;3;SG;IND;PST",
    "V;1;PL;IND;PST", "V;2;PL;IND;PST", "V;3;PL;IND;PST",
    "V;1;SG;ADM;PRS", "V;2;SG;ADM;PRS", "V;3;SG;ADM;PRS",
    "V;1;PL;ADM;PRS", "V;2;PL;ADM;PRS", "V;3;PL;ADM;PRS",
    "V;1;SG;ADM;IPFV", "V;2;SG;ADM;IPFV", "V;3;SG;ADM;IPFV",
    "V;1;PL;ADM;IPFV", "V;2;PL;ADM;IPFV", "V;3;PL;ADM;IPFV",
    "V;2;SG;IMP", "V;2;PL;IMP", "V;V.PTCP",
]

# -oj class endings by paradigm, keyed by "person;number".
ENDINGS = {
    "IND;PRS": {"1;SG": "oj", "2;SG": "on", "3;SG": "on", "1;PL": "ojmë", "2;PL": "oni", "3;PL": "ojnë"},
    "IND;IPFV": {"1;SG": "oja", "2;SG": "oje", "3;SG": "onte", "1;PL": "onim", "2;PL": "onit", "3;PL": "onin"},
    "IND;PST": {"1;SG": "ova", "2;SG": "ove", "3;SG": "oi", "1;PL": "uam", "2;PL": "uat", "3;PL": "uan"},
    "ADM;PRS": {"1;SG": "uakam", "2;SG": "uake", "3;SG": "uaka", "1;PL": "uakemi", "2;PL": "uakeni", "3;PL": "uakan"},
    "ADM;IPFV": {"1;SG": "uakësha", "2;SG": "uakëshe", "3;SG": "uakësh", "1;PL": "uakëshim", "2;PL": "uakëshit", "3;PL": "uakëshin"},
}


def productive(cit, feat):
    if not cit.endswith("oj"):
        return None
    stem = cit[:-2]
    if feat == "V;V.PTCP":
        return stem + "uar"
    if feat == "V;2;SG;IMP":
        return stem + "o"
    if feat == "V;2;PL;IMP":
        return stem + "oni"
    body = feat[2:]  # e.g. "1;SG;IND;PRS"
    parts = body.split(";")
    pn = parts[0] + ";" + parts[1]
    para = ";".join(parts[2:])
    table = ENDINGS.get(para)
    return stem + table[pn] if table and pn in table else None


def main(uni_path, kai_path):
    def read(path):
        d = defaultdict(set)
        for l in open(path):
            a = l.rstrip("\n").split("\t")
            if len(a) >= 3 and a[2].startswith("V") and " " not in a[1] and "LGSPEC" not in a[2]:
                d[(a[0], a[2])].add(a[1])
        return d
    uni, kai = read(uni_path), read(kai_path)

    def chosen(lemma, feat):
        a, b = uni.get((lemma, feat), set()), kai.get((lemma, feat), set())
        pool = (a & b) or a or b
        return sorted(pool)[0] if pool else None

    lemmas = sorted({l for (l, f) in list(uni) + list(kai) if f == "V;1;SG;IND;PRS"})
    print("# lemma(1sg.pres)\t" + "\t".join(CELLS) + '  ("-" = productive -oj default)')
    for lemma in lemmas:
        if not lemma or " " in lemma:
            continue
        out = []
        for c in CELLS:
            f = chosen(lemma, c)
            out.append(f if f and f != productive(lemma, c) else "-")
        if any(x != "-" for x in out):
            print(lemma + "\t" + "\t".join(out))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
