#!/usr/bin/env python3
"""Occitan productive conjugation rules + mined exceptions, from the two
oracle TSVs (UniMorph ∩ kaikki.org).

Occitan is cited by its infinitive. Two conjugation classes are genuinely
productive and generated by rule (see productive(), mirrored exactly in
src/oci.rs):

  * the -ar class (parlar): the whole synthetic paradigm from the bare
    stem — present -i/-as/-a/-am/-atz/-an, imperfect -av-, preterite -èr-,
    future -ar-, conditional -ari-, present subjunctive -e, imperfect
    subjunctive -èss-, the three imperatives, the -at participle and -ant
    gerund;
  * the inchoative -ir class (brandir, establir): the -iss-/-isc-/-iguèr-
    augmented paradigm.

Everything else — the athematic -er/-re verbs, the short (non-inchoative)
-ir verbs (dormir, venir), and every stem/spelling irregularity of an -ar
or -ir verb — is lexical and mined into data/oci/parts.tsv, one column per
cell, "-" meaning "the productive rule is already right". Where the two
oracles attest the same form we store the agreed spelling; otherwise the
UniMorph reading. Oracle-vs-oracle disagreements are excluded by the
golden harness, so they are never mined.

Usage: mine.py data/oci/unimorph.tsv data/oci/kaikki.tsv > data/oci/parts.tsv
"""
import sys
from collections import defaultdict

# Column order of parts.tsv = the scored paradigm (48 cells).
CELLS = [
    "V;IND;PRS;1;SG", "V;IND;PRS;2;SG", "V;IND;PRS;3;SG",
    "V;IND;PRS;1;PL", "V;IND;PRS;2;PL", "V;IND;PRS;3;PL",
    "V;IND;PST;1;SG;IPFV", "V;IND;PST;2;SG;IPFV", "V;IND;PST;3;SG;IPFV",
    "V;IND;PST;1;PL;IPFV", "V;IND;PST;2;PL;IPFV", "V;IND;PST;3;PL;IPFV",
    "V;IND;PST;1;SG;PFV", "V;IND;PST;2;SG;PFV", "V;IND;PST;3;SG;PFV",
    "V;IND;PST;1;PL;PFV", "V;IND;PST;2;PL;PFV", "V;IND;PST;3;PL;PFV",
    "V;1;SG;IND;FUT", "V;2;SG;IND;FUT", "V;3;SG;IND;FUT",
    "V;1;PL;IND;FUT", "V;2;PL;IND;FUT", "V;3;PL;IND;FUT",
    "V;1;SG;COND", "V;2;SG;COND", "V;3;SG;COND",
    "V;1;PL;COND", "V;2;PL;COND", "V;3;PL;COND",
    "V;1;SG;SBJV;PRS", "V;2;SG;SBJV;PRS", "V;3;SG;SBJV;PRS",
    "V;1;PL;SBJV;PRS", "V;2;PL;SBJV;PRS", "V;3;PL;SBJV;PRS",
    "V;1;SG;SBJV;PST;IPFV", "V;2;SG;SBJV;PST;IPFV", "V;3;SG;SBJV;PST;IPFV",
    "V;1;PL;SBJV;PST;IPFV", "V;2;PL;SBJV;PST;IPFV", "V;3;PL;SBJV;PST;IPFV",
    "V;2;SG;IMP", "V;1;PL;IMP", "V;2;PL;IMP",
    "V;NFIN", "V.PTCP;PST", "V.CVB;PRS",
]

# Per-class ending tables, keyed by cell, from the bare stem
# (infinitive minus the final two characters).
AR = {
    "V;IND;PRS;1;SG": "i", "V;IND;PRS;2;SG": "as", "V;IND;PRS;3;SG": "a",
    "V;IND;PRS;1;PL": "am", "V;IND;PRS;2;PL": "atz", "V;IND;PRS;3;PL": "an",
    "V;IND;PST;1;SG;IPFV": "avi", "V;IND;PST;2;SG;IPFV": "avas",
    "V;IND;PST;3;SG;IPFV": "ava", "V;IND;PST;1;PL;IPFV": "àvem",
    "V;IND;PST;2;PL;IPFV": "àvetz", "V;IND;PST;3;PL;IPFV": "avan",
    "V;IND;PST;1;SG;PFV": "èri", "V;IND;PST;2;SG;PFV": "ères",
    "V;IND;PST;3;SG;PFV": "èt", "V;IND;PST;1;PL;PFV": "èrem",
    "V;IND;PST;2;PL;PFV": "èretz", "V;IND;PST;3;PL;PFV": "èron",
    "V;1;SG;IND;FUT": "arai", "V;2;SG;IND;FUT": "aràs", "V;3;SG;IND;FUT": "arà",
    "V;1;PL;IND;FUT": "arem", "V;2;PL;IND;FUT": "aretz", "V;3;PL;IND;FUT": "aràn",
    "V;1;SG;COND": "ariái", "V;2;SG;COND": "ariás", "V;3;SG;COND": "ariá",
    "V;1;PL;COND": "ariam", "V;2;PL;COND": "ariatz", "V;3;PL;COND": "arián",
    "V;1;SG;SBJV;PRS": "e", "V;2;SG;SBJV;PRS": "es", "V;3;SG;SBJV;PRS": "e",
    "V;1;PL;SBJV;PRS": "em", "V;2;PL;SBJV;PRS": "etz", "V;3;PL;SBJV;PRS": "en",
    "V;1;SG;SBJV;PST;IPFV": "èssi", "V;2;SG;SBJV;PST;IPFV": "èsses",
    "V;3;SG;SBJV;PST;IPFV": "èsse", "V;1;PL;SBJV;PST;IPFV": "èssem",
    "V;2;PL;SBJV;PST;IPFV": "èssetz", "V;3;PL;SBJV;PST;IPFV": "èsson",
    "V;2;SG;IMP": "a", "V;1;PL;IMP": "em", "V;2;PL;IMP": "atz",
    "V;NFIN": "ar", "V.PTCP;PST": "at", "V.CVB;PRS": "ant",
}
IR = {
    "V;IND;PRS;1;SG": "issi", "V;IND;PRS;2;SG": "isses", "V;IND;PRS;3;SG": "ís",
    "V;IND;PRS;1;PL": "issèm", "V;IND;PRS;2;PL": "issètz", "V;IND;PRS;3;PL": "isson",
    "V;IND;PST;1;SG;IPFV": "issiái", "V;IND;PST;2;SG;IPFV": "issiás",
    "V;IND;PST;3;SG;IPFV": "issiá", "V;IND;PST;1;PL;IPFV": "issiam",
    "V;IND;PST;2;PL;IPFV": "issiatz", "V;IND;PST;3;PL;IPFV": "issián",
    "V;IND;PST;1;SG;PFV": "iguèri", "V;IND;PST;2;SG;PFV": "iguères",
    "V;IND;PST;3;SG;PFV": "iguèt", "V;IND;PST;1;PL;PFV": "iguèrem",
    "V;IND;PST;2;PL;PFV": "iguèretz", "V;IND;PST;3;PL;PFV": "iguèron",
    "V;1;SG;IND;FUT": "irai", "V;2;SG;IND;FUT": "iràs", "V;3;SG;IND;FUT": "irà",
    "V;1;PL;IND;FUT": "irem", "V;2;PL;IND;FUT": "iretz", "V;3;PL;IND;FUT": "iràn",
    "V;1;SG;COND": "iriái", "V;2;SG;COND": "iriás", "V;3;SG;COND": "iriá",
    "V;1;PL;COND": "iriam", "V;2;PL;COND": "iriatz", "V;3;PL;COND": "irián",
    "V;1;SG;SBJV;PRS": "isca", "V;2;SG;SBJV;PRS": "iscas", "V;3;SG;SBJV;PRS": "isca",
    "V;1;PL;SBJV;PRS": "iscam", "V;2;PL;SBJV;PRS": "iscatz", "V;3;PL;SBJV;PRS": "iscan",
    "V;1;SG;SBJV;PST;IPFV": "iguèsse", "V;2;SG;SBJV;PST;IPFV": "iguèsses",
    "V;3;SG;SBJV;PST;IPFV": "iguèsse", "V;1;PL;SBJV;PST;IPFV": "iguèssem",
    "V;2;PL;SBJV;PST;IPFV": "iguèssetz", "V;3;PL;SBJV;PST;IPFV": "iguèsson",
    "V;2;SG;IMP": "ís", "V;1;PL;IMP": "iscam", "V;2;PL;IMP": "issetz",
    "V;NFIN": "ir", "V.PTCP;PST": "it", "V.CVB;PRS": "issent",
}


def productive(cit, feat):
    """The productive -ar / inchoative -ir form, or None for other verbs."""
    if cit.endswith("ar"):
        table = AR
    elif cit.endswith("ir"):
        table = IR
    else:
        return None
    end = table.get(feat)
    return cit[:-2] + end if end is not None else None


def main(uni_path, kai_path):
    def read(path):
        d = defaultdict(set)
        for l in open(path):
            a = l.rstrip("\n").split("\t")
            if len(a) >= 3 and a[2].startswith("V"):
                d[(a[0], a[2])].add(a[1])
        return d
    uni, kai = read(uni_path), read(kai_path)

    def agreed(lemma, feat):
        """The set of forms the golden gold accepts for a cell: the two
        oracles' union where they overlap, else empty (disagreement /
        single-oracle cells are out of golden scope)."""
        a, b = uni.get((lemma, feat), set()), kai.get((lemma, feat), set())
        return (a | b) if (a & b) else set()

    def chosen(lemma, feat):
        s = agreed(lemma, feat)
        return sorted(s)[0] if s else None

    lemmas = sorted({l for (l, f) in list(uni) + list(kai)})

    # Rule accuracy over the golden-scored cells (both oracles agree),
    # measuring the productive rules alone before any mining.
    total = hit = 0
    parts = {}
    for lemma in lemmas:
        if not lemma or " " in lemma:
            continue
        row = {}
        for c in CELLS:
            agr = agreed(lemma, c)
            pred = productive(lemma, c)
            if agr:
                total += 1
                if pred in agr:
                    hit += 1
            f = chosen(lemma, c)
            row[c] = f if (f is not None and f != pred) else "-"
        if any(v != "-" for v in row.values()):
            parts[lemma] = row

    sys.stderr.write(
        f"rule accuracy: {hit}/{total} = {100*hit/max(total,1):.2f}%, "
        f"mined lemmas: {len(parts)}\n")
    print("# lemma(infinitive)\t" + "\t".join(CELLS) + '  ("-" = productive default)')
    for lemma in sorted(parts):
        print(lemma + "\t" + "\t".join(parts[lemma][c] for c in CELLS))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
