#!/usr/bin/env python3
"""Mine the Bulgarian exception table from the two oracle TSVs.

Bulgarian is cited by its 1sg present. Two things are productive and are
generated by rule (see productive(), mirrored in src/bul.rs):

  * the a-conjugation present (citation in -ам / -ям): -ам/-аш/-а/-аме/
    -ате/-ат (and the -ям palatal variant);
  * the definite article on every participle and the verbal noun — the
    indefinite base plus -ият/-ия (masc subj/obj), -та (fem), -то (neut),
    -те (plural). So only the indefinite bases are ever stored.

Everything else is lexical and mined: the e-conjugation presents (with
their к→ч / г→ж mutations), the aorist and imperfect (person/number), the
imperative, the indefinite bases of the aorist and imperfect (NFH)
l-participles, the present and passive participles, the verbal noun, the
converb and the composite verbal-noun plural. Where the two oracles attest
the same form we store that; otherwise the UniMorph reading.

Usage: mine.py data/bul/unimorph.tsv data/bul/kaikki.tsv > data/bul/parts.tsv
"""
import sys
from collections import defaultdict

# Column order of parts.tsv: only the cells the engine must store (the
# indefinite/finite cells; definite forms are derived, so absent here).
CELLS = [
    "V;IND;PRS;1;SG", "V;IND;PRS;2;SG", "V;IND;PRS;3;SG",
    "V;IND;PRS;1;PL", "V;IND;PRS;2;PL", "V;IND;PRS;3;PL",
    "V;IND;PST;1;SG", "V;IND;PST;2;SG", "V;IND;PST;3;SG",
    "V;IND;PST;1;PL", "V;IND;PST;2;PL", "V;IND;PST;3;PL",
    "V;IND;PROG;PST;1;SG", "V;IND;PROG;PST;2;SG", "V;IND;PROG;PST;3;SG",
    "V;IND;PROG;PST;1;PL", "V;IND;PROG;PST;2;PL", "V;IND;PROG;PST;3;PL",
    "V;IMP;2;SG", "V;IMP;2;PL", "V.CVB",
    "V.PTCP;ACT;PST;MASC;SG;INDF", "V.PTCP;ACT;PST;FEM;SG;INDF",
    "V.PTCP;ACT;PST;NEUT;SG;INDF", "V.PTCP;ACT;PST;PL;INDF",
    "V.PTCP;ACT;PST;NFH;MASC;SG;INDF", "V.PTCP;ACT;PST;NFH;FEM;SG;INDF",
    "V.PTCP;ACT;PST;NFH;NEUT;SG;INDF", "V.PTCP;ACT;PST;NFH;PL;INDF",
    "V.PTCP;ACT;PRS;MASC;SG;INDF", "V.PTCP;ACT;PRS;FEM;SG;INDF",
    "V.PTCP;ACT;PRS;NEUT;SG;INDF", "V.PTCP;ACT;PRS;PL;INDF",
    "V.PTCP;PASS;PST;MASC;SG;INDF", "V.PTCP;PASS;PST;FEM;SG;INDF",
    "V.PTCP;PASS;PST;NEUT;SG;INDF", "V.PTCP;PASS;PST;PL;INDF",
    "V.MSDR;NEUT;SG;INDF", "V.MSDR;PL;INDF",
]


def article(base, feat):
    """Definite form of an indefinite base for a DEF feature."""
    if ";MASC;" in feat:
        return base + ("ия" if feat.endswith("ACC") else "ият")
    if ";FEM;" in feat:
        return base + "та"
    if ";NEUT;" in feat:
        return base + "то"
    if ";PL;" in feat:
        return base + ("та" if feat.startswith("V.MSDR") else "те")
    return None


def indef_of(feat):
    """The indefinite-base feature a definite feature derives from."""
    return feat.replace(";DEF;NOM", ";INDF").replace(";DEF;ACC", ";INDF") \
               .replace(";DEF", ";INDF")


def present_a(cit, feat):
    """a-conjugation present, or None if the citation is not -ам/-ям."""
    if cit.endswith("ам"):
        s, j = cit[:-2], "а"
    elif cit.endswith("ям"):
        s, j = cit[:-2], "я"
    else:
        return None
    end = {"1;SG": j + "м", "2;SG": j + "ш", "3;SG": j,
           "1;PL": j + "ме", "2;PL": j + "те", "3;PL": j + "т"}
    return s + end[feat[len("V;IND;PRS;"):]] if feat.startswith("V;IND;PRS;") else None


def main(uni_path, kai_path):
    def read(path):
        d = defaultdict(set)
        for l in open(path):
            a = l.rstrip("\n").split("\t")
            if len(a) >= 3 and a[2].startswith("V"):
                d[(a[0], a[2])].add(a[1])
        return d
    uni, kai = read(uni_path), read(kai_path)

    def chosen(lemma, feat):
        a, b = uni.get((lemma, feat), set()), kai.get((lemma, feat), set())
        pool = (a & b) or a or b
        return sorted(pool)[0] if pool else None

    lemmas = sorted({l for (l, f) in list(uni) + list(kai) if f == "V;IND;PRS;1;SG"})

    def productive(lemma, feat):
        if feat.startswith("V;IND;PRS;"):
            return present_a(lemma, feat)
        if "DEF" in feat:
            base = chosen(lemma, indef_of(feat))
            return article(base, feat) if base else None
        return None

    print("# lemma(1sg.pres)\t" + "\t".join(CELLS) + '  ("-" = productive default)')
    for lemma in lemmas:
        if not lemma or " " in lemma:
            continue
        out = []
        for c in CELLS:
            f = chosen(lemma, c)
            out.append(f if f and f != productive(lemma, c) else "-")
        if any(x != "-" for x in out):
            print(lemma + "\t" + "\t".join(out))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
