#!/usr/bin/env python3
"""Tatar productive vowel-harmony rules + mined exceptions.

Kazan Tatar (Cyrillic) is agglutinative with two-way backness harmony.
Cited by the verbal noun in -у / -ү, the stem is the citation minus that
final vowel. From the stem the synthetic core is generated by rule
(mirrored in src/tat.rs):

  * present     stem + A            (бар→бара, кер→керә); vowel-final stems
                                     drop the vowel and take -ый/-и
  * past def.   stem + (д|т)+H      (-ды/-де, -ты/-те after a voiceless C)
  * aorist/fut  stem + A + р        (-ар/-әр); many stems take -ыр/-ер
                                     instead — those are mined
  * conditional stem + с + A        (-са/-сә)
  * imperative  2sg = stem, 2pl = stem+H+гыз/гез

with backness harmony A = а/ә, H = ы/е and the agreement suffixes below.
Every form the rules get wrong is mined into data/tat/parts.tsv (single
oracle: kaikki — Beta tier).

Usage: mine.py data/tat/kaikki.tsv > data/tat/parts.tsv"""
import sys
from collections import defaultdict

BACK = "аоуыяю"          # back vowels (я/ю carry back a/u)
VOWELS = "аоуыяюәөүеэи"
VOICELESS = "кпстфхцчшщ"

CELLS = [
    "V;PRS;1;SG", "V;PRS;2;SG", "V;PRS;3;SG",
    "V;PRS;1;PL", "V;PRS;2;PL", "V;PRS;3;PL",
    "V;PST;1;SG", "V;PST;2;SG", "V;PST;3;SG",
    "V;PST;1;PL", "V;PST;2;PL", "V;PST;3;PL",
    "V;FUT;1;SG", "V;FUT;2;SG", "V;FUT;3;SG",
    "V;FUT;1;PL", "V;FUT;2;PL", "V;FUT;3;PL",
    "V;COND;1;SG", "V;COND;2;SG", "V;COND;3;SG",
    "V;COND;1;PL", "V;COND;2;PL", "V;COND;3;PL",
    "V;IMP;2;SG", "V;IMP;2;PL", "V;NFIN",
]


def harmony(stem):
    """(A low vowel, H high vowel) from the stem's last vowel."""
    v = next((c for c in reversed(stem) if c in VOWELS), "а")
    back = v in BACK
    return ("а", "ы") if back else ("ә", "е")


def stem_of(cit):
    """Verbal-noun citation minus its final -у / -ү."""
    return cit[:-1] if cit and cit[-1] in "уү" else cit


def produce(cit, feat):
    if not (cit.endswith("у") or cit.endswith("ү")):
        return None
    if feat == "V;NFIN":
        return cit
    stem = stem_of(cit)
    if not stem:
        return None
    A, H = harmony(stem)
    # Only the low vowels а/ә contract before the present and take the bare
    # -р aorist; и/у/ү-final stems behave like consonant-final ones.
    vowel_final = stem[-1] in "аә"
    last = stem[-1]

    # present-tense agreement (marker -а/-ә already attached)
    prs = {"1;SG": "м", "2;SG": "с" + H + "ң", "3;SG": "",
           "1;PL": "б" + H + "з", "2;PL": "с" + H + "з", "3;PL": "л" + A + "р"}
    # aorist/future agreement (copular: 1sg -мын/-мен)
    fut = dict(prs, **{"1;SG": "м" + H + "н"})
    # past/conditional agreement
    pst = {"1;SG": "м", "2;SG": "ң", "3;SG": "",
           "1;PL": "к", "2;PL": "г" + H + "з", "3;PL": "л" + A + "р"}

    if feat == "V;IMP;2;SG":
        return stem
    if feat == "V;IMP;2;PL":
        return stem + ("гыз" if A == "а" else "гез") if vowel_final \
            else stem + H + ("гыз" if A == "а" else "гез")

    parts = feat.split(";")
    tense, pn = parts[1], parts[2] + ";" + parts[3]
    if tense == "PRS":
        if vowel_final:
            base = stem[:-1] + ("ый" if A == "а" else "и")
        else:
            base = stem + A
        return base + prs[pn]
    if tense == "PST":
        d = "т" if last in VOICELESS else "д"
        return stem + d + H + pst[pn]
    if tense == "COND":
        return stem + "с" + A + pst[pn]
    if tense == "FUT":
        # Aorist vowel: bare -р after an а/ә stem, else high -ыр/-ер for a
        # polysyllabic stem and low -ар/-әр for a monosyllabic one.
        if vowel_final:
            marker = "р"
        else:
            nvowels = sum(1 for c in stem if c in VOWELS)
            marker = (H if nvowels >= 2 else A) + "р"
        return stem + marker + fut[pn]
    return None


def main(path):
    gold = defaultdict(dict)
    for line in open(path):
        a = line.rstrip("\n").split("\t")
        if len(a) >= 3:
            gold[a[0]].setdefault(a[2], set()).add(a[1])
    total = hit = 0
    parts = {}
    for cit, cells in gold.items():
        row = {}
        for feat, forms in cells.items():
            if feat not in CELLS:
                continue
            pred = produce(cit, feat)
            if pred is None:
                continue
            total += 1
            if pred in forms:
                hit += 1
            else:
                row[feat] = sorted(forms)[0]
        if row:
            parts[cit] = row
    sys.stderr.write(
        f"rule accuracy: {hit}/{total} = {100 * hit / max(total, 1):.2f}%, "
        f"mined lemmas: {len(parts)}\n")
    print("# lemma(verbal-noun)\t" + "\t".join(CELLS))
    for cit in sorted(parts):
        print(cit + "\t" + "\t".join(parts[cit].get(c, "-") for c in CELLS))


if __name__ == "__main__":
    main(sys.argv[1])
