#!/usr/bin/env python3
"""Compile the per-language correctness table (docs/correctness.md) from the
stats each golden harness emits (target/stats_<lang>.json).

Usage: python3 scripts/correctness.py [--run]

  --run   first run every golden_<lang> whose gold data is present, so the
          stats JSONs are fresh. Without it, the script reads whatever
          target/stats_*.json already exist.

Tiers (a language only ships once it is at least Beta — 100% on one oracle):
  Verified       100% on the two-oracle agreement, every paradigm slot
                 covered, and every oracle disagreement resolved in
                 docs/<lang>/disagreements.tsv.
  Verified·gaps  100% on agreement, but with uncovered slots and/or
                 unresolved disagreements ("missing bits").
  Beta           100% against a single oracle (no independent second
                 oracle that overlaps enough to form the agreement loop).
"""
import glob
import json
import os
import re
import subprocess
import sys
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NAMES = {
    "deu": "German", "fra": "French", "spa": "Spanish", "por": "Portuguese",
    "ita": "Italian", "ron": "Romanian", "swe": "Swedish", "eng": "English",
    "dan": "Danish", "ces": "Czech", "slv": "Slovenian", "est": "Estonian",
    "fin": "Finnish", "gle": "Irish", "cat": "Catalan", "ukr": "Ukrainian",
    "isl": "Icelandic", "jpn": "Japanese", "kor": "Korean", "nld": "Dutch",
    "rus": "Russian", "hye": "Armenian", "tur": "Turkish",
}


def crate_version():
    txt = open(os.path.join(ROOT, "Cargo.toml"), encoding="utf-8").read()
    return re.search(r'^version = "([^"]+)"', txt, re.M).group(1)


def golden_bin(lang):
    return f"golden_{lang}"


def golden_langs():
    langs = ["deu"] + [
        os.path.basename(p)[len("golden_"):-len(".rs")]
        for p in glob.glob(os.path.join(ROOT, "src/bin/golden_*.rs"))
    ]
    return sorted(set(langs))


def run_goldens(langs):
    for lang in langs:
        b = golden_bin(lang)
        print(f"running {b} …", file=sys.stderr)
        r = subprocess.run(
            ["cargo", "run", "--release", "--quiet", "--bin", b],
            cwd=ROOT, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
        if r.returncode != 0:
            print(f"  skipped {lang} (gold data missing)", file=sys.stderr)


def tier(s):
    if s["single_oracle"]:
        return "Beta"
    clean = (
        s["agreed_pct"] >= 99.9995
        and not s["uncovered_slots"]
        and s["resolution"]["unresolved"] == 0
    )
    return "Verified" if clean else "Verified·gaps"


def load_stats():
    out = {}
    for p in glob.glob(os.path.join(ROOT, "target/stats_*.json")):
        s = json.load(open(p, encoding="utf-8"))
        out[s["lang"]] = s
    return out


def table(stats):
    rows = []
    for lang in sorted(stats, key=lambda l: NAMES.get(l, l)):
        s = stats[lang]
        name = NAMES.get(lang, lang)
        oracles = " ∩ ".join(o.replace(".tsv", "") for o in s["oracles"])
        agreed = f'{s["agreed_matched"]:,} / {s["agreed_forms"]:,}'
        apct = f'{s["agreed_pct"]:.2f}%'
        slots = f'{s["slot_types_covered"]}/{s["slot_types"]}'
        if s["single_oracle"]:
            disc = "—"
        else:
            disc = f'{s["disagreements_resolved"]}/{s["disagreements"]}'
        rows.append(
            f"| {name} | {oracles} | {agreed} | {apct} | {slots} | {disc} | {tier(s)} |"
        )
    return "\n".join(rows)


def main():
    langs = golden_langs()
    if "--run" in sys.argv:
        run_goldens(langs)
    stats = load_stats()
    ver = crate_version()
    counts = {}
    for lang in stats:
        counts[tier(stats[lang])] = counts.get(tier(stats[lang]), 0) + 1
    summary = ", ".join(f"{n} {t}" for t, n in sorted(counts.items()))
    md = f"""# Correctness

How every language is verified, measured at test time. Generated by
`scripts/correctness.py` from the golden harness; regenerate on each
release.

**ablaut {ver}** — {len(stats)} languages: {summary}.

Each language is scored on the slots where its two independent oracles
agree (a Wiktionary extraction crossed with a national/academic lexicon).
The engine hits 100% there; the residual is the two oracles disagreeing
with *each other*, which is ruled on in `docs/<lang>/disagreements.tsv`.

- **Agreed forms** — engine matches / slots the two oracles agree on.
- **Slots** — paradigm slot types the engine covers / present in the gold
  (a shortfall is an uncovered tense).
- **Disagreements** — oracle-vs-oracle splits resolved / total.

## Tiers

- **Verified** — 100% on agreement, full slot coverage, every disagreement
  resolved.
- **Verified·gaps** — 100% on agreement, but with uncovered slots and/or
  unresolved disagreements.
- **Beta** — 100% against a single oracle (no overlapping independent
  second oracle yet).

Everything shipped is at least Beta: 100% correct on one oracle.

| Language | Oracles | Agreed forms | Agreed % | Slots | Disagreements | Tier |
|---|---|---:|---:|:---:|:---:|:---|
{table(stats)}

German's CI regression gate is the original `src/bin/golden.rs` (it keeps
German's covered/fallback split and corrupt-lemma exclusion); the row
above is the same feature→form mapping scored through the shared harness
(`golden_deu`) so German sits on the two-oracle footing as everyone else.
"""
    out = os.path.join(ROOT, "docs/correctness.md")
    open(out, "w", encoding="utf-8").write(md)

    # Structured export for downstream consumers (e.g. the /trust page).
    export = {
        "version": ver,
        "languages": [
            {
                "name": NAMES.get(l, l),
                "code": l,
                "oracles": [o.replace(".tsv", "") for o in stats[l]["oracles"]],
                "agreed_matched": stats[l]["agreed_matched"],
                "agreed_forms": stats[l]["agreed_forms"],
                "agreed_pct": round(stats[l]["agreed_pct"], 4),
                "slot_types_covered": stats[l]["slot_types_covered"],
                "slot_types": stats[l]["slot_types"],
                "disagreements": stats[l]["disagreements"],
                "disagreements_resolved": stats[l]["disagreements_resolved"],
                "single_oracle": stats[l]["single_oracle"],
                "tier": tier(stats[l]),
            }
            for l in sorted(stats, key=lambda l: NAMES.get(l, l))
        ],
    }
    jout = os.path.join(ROOT, "docs/correctness.json")
    open(jout, "w", encoding="utf-8").write(json.dumps(export, ensure_ascii=False, indent=2))

    hist = write_history(ver, export)
    print(
        f"wrote {out}, {jout} and docs/correctness-history.json "
        f"({len(stats)} languages, {len(hist)} versions)"
    )


def write_history(ver, export):
    """Append this release's aggregate to docs/correctness-history.json so
    /accuracy can show progression across versions. Idempotent: re-running
    for the same version replaces that version's entry. Built from `export`
    (the same numbers written to correctness.json) so the two never drift.
    """
    path = os.path.join(ROOT, "docs/correctness-history.json")
    try:
        history = json.load(open(path, encoding="utf-8"))
    except (FileNotFoundError, ValueError):
        history = []
    langs = export["languages"]
    matched = sum(l["agreed_matched"] for l in langs)
    agreed = sum(l["agreed_forms"] for l in langs)
    tiers = {}
    for l in langs:
        tiers[l["tier"]] = tiers.get(l["tier"], 0) + 1
    entry = {
        "version": ver,
        "date": date.today().isoformat(),
        "languages": len(langs),
        "verified_forms": matched,
        "agreed_forms": agreed,
        "agreed_pct": round(100 * matched / agreed, 4) if agreed else 0.0,
        "tiers": tiers,
        "per_language": [
            {
                "code": l["code"],
                "name": l["name"],
                "agreed_pct": l["agreed_pct"],
                "agreed_matched": l["agreed_matched"],
                "tier": l["tier"],
            }
            for l in langs
        ],
    }
    history = [h for h in history if h.get("version") != ver] + [entry]
    history.sort(key=lambda h: tuple(int(x) for x in re.findall(r"\d+", h["version"])))
    open(path, "w", encoding="utf-8").write(json.dumps(history, ensure_ascii=False, indent=2))
    return history


if __name__ == "__main__":
    main()
