//! Belarusian conjugation. Belarusian is cited by its infinitive (in
//! -ць / -ці / -чы, and -цца for reflexives). One set of endings is
//! genuinely productive and generated by rule (mirrored from
//! `scripts/bel/mine.py::productive`):
//!
//!   * the non-past — the present of imperfective verbs and the synthetic
//!     future of perfective ones share one paradigm; the endings follow
//!     the infinitive class (-аваць/-яваць → -ую/-юю, -нуць and other hard
//!     stems → -у…-уць, first-conjugation vowel stems -аць/-яць → -ю…-юць,
//!     second-conjugation soft -іць → -ю/-іш/…/-яць and hard -ыць →
//!     -у/-ыш/…/-аць);
//!   * the past l-participle: infinitive stem + -ў / -ла / -ла / -лі;
//!   * the imperative: -й after a vowel stem, -і/-ы after a consonant.
//!
//! What the rules cannot predict is lexical and carries a mined row in
//! `data/bel/parts.tsv`: the akanne / jakanne root alternations of the
//! non-past (зрабіць → зробіць, абараніць → абароніць), consonant
//! mutations (адказаць → адкажу), soft-sign imperatives (абносіць →
//! абнось), the reflexive (-цца) verbs and the athematic irregulars
//! (даць, быць, ісці, магчы …). The engine is override-first: a mined
//! cell wins, otherwise the productive rule applies.

use std::collections::HashMap;
use std::sync::OnceLock;

/// The stored cells, in the column order of `data/bel/parts.tsv`.
pub const CELLS: [&str; 18] = [
    "V;PRS;1;SG",
    "V;PRS;2;SG",
    "V;PRS;3;SG",
    "V;PRS;1;PL",
    "V;PRS;2;PL",
    "V;PRS;3;PL",
    "V;FUT;1;SG",
    "V;FUT;2;SG",
    "V;FUT;3;SG",
    "V;FUT;1;PL",
    "V;FUT;2;PL",
    "V;FUT;3;PL",
    "V;PST;SG;MASC",
    "V;PST;SG;FEM",
    "V;PST;SG;NEUT",
    "V;PST;PL",
    "V;IMP;2;SG",
    "V;IMP;2;PL",
];

/// Why a form cannot be produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The input does not look like a Belarusian infinitive.
    NotAVerb,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "not a Belarusian verb")
    }
}

static PARTS_TSV: &str = include_str!("../data/bel/parts.tsv");

fn overrides(lemma: &str) -> Option<HashMap<&'static str, &'static str>> {
    static MAP: OnceLock<HashMap<&'static str, HashMap<&'static str, &'static str>>> =
        OnceLock::new();
    let map = MAP.get_or_init(|| {
        let mut m = HashMap::new();
        for line in PARTS_TSV.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let mut cols = line.split('\t');
            let Some(lemma) = cols.next() else { continue };
            let mut row = HashMap::new();
            for (i, val) in cols.enumerate() {
                if val != "-" && !val.is_empty() {
                    if let Some(feat) = CELLS.get(i) {
                        row.insert(*feat, val);
                    }
                }
            }
            m.insert(lemma, row);
        }
        m
    });
    map.get(lemma).cloned()
}

/// The person;number tail of a non-past feature ("1;SG" …).
fn person_number(feat: &str) -> Option<&str> {
    feat.splitn(3, ';').nth(2)
}

/// One non-past personal ending for a conjugation table.
fn ending(pn: &str, endings: &[(&'static str, &'static str); 6]) -> Option<&'static str> {
    endings.iter().find(|(k, _)| *k == pn).map(|(_, v)| *v)
}

// The non-past personal endings, by conjugation. A verb's present (if
// imperfective) and synthetic future (if perfective) use the same set.
const CONJ1: [(&str, &str); 6] = [
    ("1;SG", "ю"),
    ("2;SG", "еш"),
    ("3;SG", "е"),
    ("1;PL", "ем"),
    ("2;PL", "еце"),
    ("3;PL", "юць"),
]; // vowel stem
const CONJ1_HARD: [(&str, &str); 6] = [
    ("1;SG", "у"),
    ("2;SG", "еш"),
    ("3;SG", "е"),
    ("1;PL", "ем"),
    ("2;PL", "еце"),
    ("3;PL", "уць"),
]; // -нуць etc.
const CONJ2_SOFT: [(&str, &str); 6] = [
    ("1;SG", "ю"),
    ("2;SG", "іш"),
    ("3;SG", "іць"),
    ("1;PL", "ім"),
    ("2;PL", "іце"),
    ("3;PL", "яць"),
]; // -іць
const CONJ2_HARD: [(&str, &str); 6] = [
    ("1;SG", "у"),
    ("2;SG", "ыш"),
    ("3;SG", "ыць"),
    ("1;PL", "ым"),
    ("2;PL", "ыце"),
    ("3;PL", "аць"),
]; // -ыць

/// Drop the last `n` Cyrillic chars from `s` and append `tail`.
fn trim(s: &str, n: usize, tail: &str) -> String {
    let keep = s.chars().count().saturating_sub(n);
    let stem: String = s.chars().take(keep).collect();
    format!("{stem}{tail}")
}

/// The productive non-past form for person;number `pn`, or None.
fn nonpast(lem: &str, pn: &str) -> Option<String> {
    for (suf, th) in [("аваць", "у"), ("яваць", "ю")] {
        if lem.ends_with(suf) {
            let e = ending(pn, &CONJ1)?;
            return Some(trim(lem, 5, &format!("{th}{e}")));
        }
    }
    if lem.ends_with("нуць") {
        return Some(trim(lem, 3, ending(pn, &CONJ1_HARD)?));
    }
    for suf in ["аць", "яць"] {
        if lem.ends_with(suf) {
            return Some(trim(lem, 2, ending(pn, &CONJ1)?));
        }
    }
    if lem.ends_with("іць") {
        return Some(trim(lem, 3, ending(pn, &CONJ2_SOFT)?));
    }
    if lem.ends_with("ыць") {
        return Some(trim(lem, 3, ending(pn, &CONJ2_HARD)?));
    }
    if lem.ends_with("ець") {
        return Some(trim(lem, 3, &format!("е{}", ending(pn, &CONJ1)?)));
    }
    None
}

/// The productive imperative (2sg / 2pl), or None.
fn imperative(lem: &str, plural: bool) -> Option<String> {
    let tail = if plural { "це" } else { "" };
    for suf in ["аваць", "яваць"] {
        if lem.ends_with(suf) {
            let th = if suf.starts_with('а') { "у" } else { "ю" };
            return Some(trim(lem, 5, &format!("{th}й{tail}")));
        }
    }
    if lem.ends_with("нуць") {
        return Some(trim(lem, 3, &format!("і{tail}")));
    }
    for suf in ["аць", "яць"] {
        if lem.ends_with(suf) {
            return Some(trim(lem, 2, &format!("й{tail}")));
        }
    }
    if lem.ends_with("іць") {
        return Some(trim(lem, 3, &format!("і{tail}")));
    }
    if lem.ends_with("ыць") {
        return Some(trim(lem, 3, &format!("ы{tail}")));
    }
    if lem.ends_with("ець") {
        return Some(trim(lem, 3, &format!("ей{tail}")));
    }
    None
}

/// The productive past l-participle, or None (only -ць infinitives).
fn past(lem: &str, feat: &str) -> Option<String> {
    if !lem.ends_with("ць") {
        return None;
    }
    let tail = match feat {
        "V;PST;SG;MASC" => "ў",
        "V;PST;SG;FEM" | "V;PST;SG;NEUT" => "ла",
        "V;PST;PL" => "лі",
        _ => return None,
    };
    Some(trim(lem, 2, tail))
}

/// A conjugatable Belarusian verb, cited by its infinitive.
#[derive(Debug, Clone)]
pub struct Verb {
    infinitive: String,
    overrides: HashMap<&'static str, &'static str>,
}

impl Verb {
    /// Build a verb from its infinitive.
    pub fn from_infinitive(infinitive: &str) -> Result<Self, Error> {
        let lowered = infinitive.trim().to_lowercase();
        let lem = if overrides(infinitive.trim()).is_none() && overrides(&lowered).is_some() {
            lowered.clone()
        } else {
            infinitive.trim().to_string()
        };
        if lem.is_empty()
            || lem.contains(char::is_whitespace)
            || !lem
                .chars()
                .all(|c| c.is_alphabetic() || c == '\'' || c == '-')
        {
            return Err(Error::NotAVerb);
        }
        let over = overrides(&lem).unwrap_or_default();
        // Accept only a conjugatable citation: a Belarusian infinitive
        // (-ць/-ці/-чы, or reflexive -цца) or a stored verb.
        let is_infinitive = lem.ends_with("ць")
            || lem.ends_with("ці")
            || lem.ends_with("чы")
            || lem.ends_with("цца");
        if over.is_empty() && !is_infinitive {
            return Err(Error::NotAVerb);
        }
        Ok(Self {
            infinitive: lem,
            overrides: over,
        })
    }

    /// The citation form (infinitive).
    pub fn citation(&self) -> &str {
        &self.infinitive
    }

    /// The form for a UniMorph feature bundle: a mined override, else the
    /// productive rule for its class.
    pub fn form(&self, feature: &str) -> Option<String> {
        if let Some(f) = self.overrides.get(feature) {
            return Some((*f).to_string());
        }
        if feature.starts_with("V;PST") {
            return past(&self.infinitive, feature);
        }
        if feature.starts_with("V;IMP") {
            return imperative(&self.infinitive, feature.ends_with("PL"));
        }
        if feature.starts_with("V;PRS") || feature.starts_with("V;FUT") {
            return nonpast(&self.infinitive, person_number(feature)?);
        }
        None
    }
}

/// A compact conjugation table — the headline forms of the paradigm,
/// shared by the WebAssembly and Python bindings.
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct Table {
    /// The infinitive (the citation).
    pub infinitive: String,
    /// Present, 1sg/2sg/3sg/1pl/2pl/3pl (imperfective verbs).
    pub present: Vec<Option<String>>,
    /// Synthetic future, same order (perfective verbs).
    pub future: Vec<Option<String>>,
    /// Past l-participle: masc/fem/neut sg, then pl.
    pub past: Vec<Option<String>>,
    /// Imperative 2sg/2pl.
    pub imperative: Vec<Option<String>>,
}

impl Table {
    #[must_use]
    pub fn build(v: &Verb) -> Self {
        let many = |feats: &[&str]| feats.iter().map(|f| v.form(f)).collect();
        Self {
            infinitive: v.citation().to_string(),
            present: many(&[
                "V;PRS;1;SG",
                "V;PRS;2;SG",
                "V;PRS;3;SG",
                "V;PRS;1;PL",
                "V;PRS;2;PL",
                "V;PRS;3;PL",
            ]),
            future: many(&[
                "V;FUT;1;SG",
                "V;FUT;2;SG",
                "V;FUT;3;SG",
                "V;FUT;1;PL",
                "V;FUT;2;PL",
                "V;FUT;3;PL",
            ]),
            past: many(&["V;PST;SG;MASC", "V;PST;SG;FEM", "V;PST;SG;NEUT", "V;PST;PL"]),
            imperative: many(&["V;IMP;2;SG", "V;IMP;2;PL"]),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(cit: &str) -> Verb {
        Verb::from_infinitive(cit).unwrap()
    }

    #[test]
    fn first_conjugation_present_productive() {
        // чытаць: vowel-stem first conjugation, no mined row.
        let g = v("чытаць");
        assert_eq!(g.form("V;PRS;1;SG").unwrap(), "чытаю");
        assert_eq!(g.form("V;PRS;2;SG").unwrap(), "чытаеш");
        assert_eq!(g.form("V;PRS;3;PL").unwrap(), "чытаюць");
        // -аваць contracts to a -у- stem.
        let m = v("маляваць");
        assert_eq!(m.form("V;PRS;1;SG").unwrap(), "малюю");
        assert_eq!(m.form("V;PRS;2;SG").unwrap(), "малюеш");
    }

    #[test]
    fn past_and_imperative_productive() {
        let g = v("чытаць");
        assert_eq!(g.form("V;PST;SG;MASC").unwrap(), "чытаў");
        assert_eq!(g.form("V;PST;SG;FEM").unwrap(), "чытала");
        assert_eq!(g.form("V;PST;PL").unwrap(), "чыталі");
        assert_eq!(g.form("V;IMP;2;SG").unwrap(), "чытай");
        assert_eq!(g.form("V;IMP;2;PL").unwrap(), "чытайце");
    }

    #[test]
    fn mined_override_wins() {
        // зрабіць shows akanne (а→о) in the future — a mined cell.
        let z = v("зрабіць");
        assert_eq!(z.form("V;FUT;3;SG").unwrap(), "зробіць");
        // The past is still productive.
        assert_eq!(z.form("V;PST;SG;MASC").unwrap(), "зрабіў");
    }

    #[test]
    fn rejects_non_verb() {
        assert!(Verb::from_infinitive("дом").is_err());
        assert!(Verb::from_infinitive("").is_err());
    }
}
