//! Bulgarian conjugation. Bulgarian is cited (no infinitive) by its 1sg
//! present. Two things are productive and generated by rule: the
//! a-conjugation present (citation in -ам / -ям), and the definite
//! article on every participle and the verbal noun — the indefinite base
//! plus -ият/-ия (masc subj/obj), -та (fem), -то (neut) and -те (plural).
//! Everything else is lexical and carries a mined row in
//! `data/bul/parts.tsv`: the e-conjugation presents (with their к→ч / г→ж
//! mutations), the aorist and imperfect, the imperative, the indefinite
//! bases of the aorist and imperfect (renarrative/NFH) l-participles, the
//! present and passive participles, the verbal noun and the converb.
//! Because the definite forms are derived, only the indefinite/finite
//! bases are stored.

use std::collections::HashMap;
use std::sync::OnceLock;

/// The stored cells, in the column order of `data/bul/parts.tsv`. The
/// definite forms are absent — they are derived from these.
pub const CELLS: [&str; 39] = [
    "V;IND;PRS;1;SG", "V;IND;PRS;2;SG", "V;IND;PRS;3;SG",
    "V;IND;PRS;1;PL", "V;IND;PRS;2;PL", "V;IND;PRS;3;PL",
    "V;IND;PST;1;SG", "V;IND;PST;2;SG", "V;IND;PST;3;SG",
    "V;IND;PST;1;PL", "V;IND;PST;2;PL", "V;IND;PST;3;PL",
    "V;IND;PROG;PST;1;SG", "V;IND;PROG;PST;2;SG", "V;IND;PROG;PST;3;SG",
    "V;IND;PROG;PST;1;PL", "V;IND;PROG;PST;2;PL", "V;IND;PROG;PST;3;PL",
    "V;IMP;2;SG", "V;IMP;2;PL", "V.CVB",
    "V.PTCP;ACT;PST;MASC;SG;INDF", "V.PTCP;ACT;PST;FEM;SG;INDF",
    "V.PTCP;ACT;PST;NEUT;SG;INDF", "V.PTCP;ACT;PST;PL;INDF",
    "V.PTCP;ACT;PST;NFH;MASC;SG;INDF", "V.PTCP;ACT;PST;NFH;FEM;SG;INDF",
    "V.PTCP;ACT;PST;NFH;NEUT;SG;INDF", "V.PTCP;ACT;PST;NFH;PL;INDF",
    "V.PTCP;ACT;PRS;MASC;SG;INDF", "V.PTCP;ACT;PRS;FEM;SG;INDF",
    "V.PTCP;ACT;PRS;NEUT;SG;INDF", "V.PTCP;ACT;PRS;PL;INDF",
    "V.PTCP;PASS;PST;MASC;SG;INDF", "V.PTCP;PASS;PST;FEM;SG;INDF",
    "V.PTCP;PASS;PST;NEUT;SG;INDF", "V.PTCP;PASS;PST;PL;INDF",
    "V.MSDR;NEUT;SG;INDF", "V.MSDR;PL;INDF",
];

/// Why a form cannot be produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The input does not look like a Bulgarian 1sg-present citation.
    NotAVerb,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "not a Bulgarian verb")
    }
}

static PARTS_TSV: &str = include_str!("../data/bul/parts.tsv");

fn overrides(cit: &str) -> Option<HashMap<&'static str, &'static str>> {
    static MAP: OnceLock<HashMap<&'static str, HashMap<&'static str, &'static str>>> =
        OnceLock::new();
    let map = MAP.get_or_init(|| {
        let mut m = HashMap::new();
        for line in PARTS_TSV.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let mut cols = line.split('\t');
            let Some(lemma) = cols.next() else { continue };
            let mut row = HashMap::new();
            for (i, val) in cols.enumerate() {
                if val != "-" && !val.is_empty() {
                    if let Some(feat) = CELLS.get(i) {
                        row.insert(*feat, val);
                    }
                }
            }
            m.insert(lemma, row);
        }
        m
    });
    map.get(cit).cloned()
}

/// The a-conjugation present, or None if the citation is not -ам/-ям.
fn present_a(cit: &str, feat: &str) -> Option<String> {
    let pn = feat.strip_prefix("V;IND;PRS;")?;
    let (s, j) = if let Some(stem) = cit.strip_suffix("ам") {
        (stem, "а")
    } else if let Some(stem) = cit.strip_suffix("ям") {
        (stem, "я")
    } else {
        return None;
    };
    let end = match pn {
        "1;SG" => format!("{j}м"),
        "2;SG" => format!("{j}ш"),
        "3;SG" => j.to_string(),
        "1;PL" => format!("{j}ме"),
        "2;PL" => format!("{j}те"),
        "3;PL" => format!("{j}т"),
        _ => return None,
    };
    Some(format!("{s}{end}"))
}

/// The indefinite-base feature a definite feature derives from.
fn indef_of(feat: &str) -> String {
    feat.replace(";DEF;NOM", ";INDF")
        .replace(";DEF;ACC", ";INDF")
        .replace(";DEF", ";INDF")
}

/// Add the definite article to an indefinite base for a DEF feature.
fn article(base: &str, feat: &str) -> Option<String> {
    Some(if feat.contains(";MASC;") {
        format!("{base}{}", if feat.ends_with("ACC") { "ия" } else { "ият" })
    } else if feat.contains(";FEM;") {
        format!("{base}та")
    } else if feat.contains(";NEUT;") {
        format!("{base}то")
    } else if feat.contains(";PL;") {
        format!("{base}{}", if feat.starts_with("V.MSDR") { "та" } else { "те" })
    } else {
        return None;
    })
}

/// A conjugatable Bulgarian verb, cited by its 1sg present.
#[derive(Debug, Clone)]
pub struct Verb {
    citation: String,
    overrides: HashMap<&'static str, &'static str>,
}

impl Verb {
    /// Build a verb from its 1sg-present citation form.
    pub fn from_infinitive(citation: &str) -> Result<Self, Error> {
        let lowered = citation.trim().to_lowercase();
        let cit = if overrides(citation.trim()).is_none() && overrides(&lowered).is_some() {
            lowered.clone()
        } else {
            citation.trim().to_string()
        };
        if cit.is_empty()
            || cit.contains(char::is_whitespace)
            || !cit.chars().all(|c| c.is_alphabetic() || c == '-')
        {
            return Err(Error::NotAVerb);
        }
        let over = overrides(&cit).unwrap_or_default();
        // Accept a citation only if we can conjugate it: it is either a
        // stored verb or an a-conjugation present.
        if over.is_empty() && !cit.ends_with("ам") && !cit.ends_with("ям") {
            return Err(Error::NotAVerb);
        }
        Ok(Self {
            citation: cit,
            overrides: over,
        })
    }

    /// The citation form (1sg present).
    pub fn citation(&self) -> &str {
        &self.citation
    }

    /// The form for a UniMorph feature bundle: a mined override, else the
    /// definite article applied to the (mined or productive) indefinite
    /// base, else the productive a-conjugation present.
    pub fn form(&self, feature: &str) -> Option<String> {
        if let Some(f) = self.overrides.get(feature) {
            return Some((*f).to_string());
        }
        if feature.contains("DEF") && !feature.contains("INDF") {
            // The masculine definite is built on the plural stem, not the
            // bare masc indefinite: Bulgarian's yat alternation (я→е) and
            // the ъ-drop surface once a syllable follows, and the plural
            // already shows them (запрял → pl запрели → запрелия/ят).
            if feature.contains(";MASC;SG;DEF") {
                let pl = self.form(
                    &feature
                        .replace(";MASC;SG;DEF;NOM", ";PL;INDF")
                        .replace(";MASC;SG;DEF;ACC", ";PL;INDF"),
                )?;
                let stem = pl.strip_suffix('и').unwrap_or(&pl);
                let suffix = if feature.ends_with("ACC") { "ия" } else { "ият" };
                return Some(format!("{stem}{suffix}"));
            }
            let base = self.form(&indef_of(feature))?;
            return article(&base, feature);
        }
        present_a(&self.citation, feature)
    }
}

/// A compact conjugation table — the headline forms of the paradigm,
/// shared by the WebAssembly and Python bindings.
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct Table {
    /// 1sg present (the citation).
    pub present: String,
    /// Present, 1sg/2sg/3sg/1pl/2pl/3pl.
    pub present_all: Vec<Option<String>>,
    /// Aorist, same order.
    pub aorist: Vec<Option<String>>,
    /// Imperfect, same order.
    pub imperfect: Vec<Option<String>>,
    /// Imperative 2sg/2pl.
    pub imperative: Vec<Option<String>>,
    /// Aorist active past l-participle: masc/fem/neut/pl (indefinite).
    pub past_participle: Vec<Option<String>>,
    /// Present active participle: masc/fem/neut/pl (indefinite).
    pub present_participle: Vec<Option<String>>,
    /// Passive past participle: masc/fem/neut/pl (indefinite).
    pub passive_participle: Vec<Option<String>>,
    pub verbal_adverb: Option<String>,
    pub verbal_noun: Option<String>,
}

impl Table {
    #[must_use]
    pub fn build(v: &Verb) -> Self {
        let many = |feats: &[&str]| feats.iter().map(|f| v.form(f)).collect();
        Self {
            present: v.citation().to_string(),
            present_all: many(&[
                "V;IND;PRS;1;SG", "V;IND;PRS;2;SG", "V;IND;PRS;3;SG",
                "V;IND;PRS;1;PL", "V;IND;PRS;2;PL", "V;IND;PRS;3;PL",
            ]),
            aorist: many(&[
                "V;IND;PST;1;SG", "V;IND;PST;2;SG", "V;IND;PST;3;SG",
                "V;IND;PST;1;PL", "V;IND;PST;2;PL", "V;IND;PST;3;PL",
            ]),
            imperfect: many(&[
                "V;IND;PROG;PST;1;SG", "V;IND;PROG;PST;2;SG", "V;IND;PROG;PST;3;SG",
                "V;IND;PROG;PST;1;PL", "V;IND;PROG;PST;2;PL", "V;IND;PROG;PST;3;PL",
            ]),
            imperative: many(&["V;IMP;2;SG", "V;IMP;2;PL"]),
            past_participle: many(&[
                "V.PTCP;ACT;PST;MASC;SG;INDF", "V.PTCP;ACT;PST;FEM;SG;INDF",
                "V.PTCP;ACT;PST;NEUT;SG;INDF", "V.PTCP;ACT;PST;PL;INDF",
            ]),
            present_participle: many(&[
                "V.PTCP;ACT;PRS;MASC;SG;INDF", "V.PTCP;ACT;PRS;FEM;SG;INDF",
                "V.PTCP;ACT;PRS;NEUT;SG;INDF", "V.PTCP;ACT;PRS;PL;INDF",
            ]),
            passive_participle: many(&[
                "V.PTCP;PASS;PST;MASC;SG;INDF", "V.PTCP;PASS;PST;FEM;SG;INDF",
                "V.PTCP;PASS;PST;NEUT;SG;INDF", "V.PTCP;PASS;PST;PL;INDF",
            ]),
            verbal_adverb: v.form("V.CVB"),
            verbal_noun: v.form("V.MSDR;NEUT;SG;INDF"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(cit: &str) -> Verb {
        Verb::from_infinitive(cit).unwrap()
    }

    #[test]
    fn a_conjugation_present_productive() {
        let g = v("гледам");
        assert_eq!(g.form("V;IND;PRS;2;SG").unwrap(), "гледаш");
        assert_eq!(g.form("V;IND;PRS;3;SG").unwrap(), "гледа");
        assert_eq!(g.form("V;IND;PRS;3;PL").unwrap(), "гледат");
        let b = v("благославям");
        assert_eq!(b.form("V;IND;PRS;2;SG").unwrap(), "благославяш");
        assert_eq!(b.form("V;IND;PRS;3;PL").unwrap(), "благославят");
    }

    #[test]
    fn definite_article_derived() {
        // Fem / neut / plural definites are the indefinite base + article.
        assert_eq!(article("играла", "V.PTCP;ACT;PST;FEM;SG;DEF").unwrap(), "игралата");
        assert_eq!(article("играло", "V.PTCP;ACT;PST;NEUT;SG;DEF").unwrap(), "игралото");
        assert_eq!(article("играли", "V.PTCP;ACT;PST;PL;DEF").unwrap(), "игралите");
        // The masculine definite is built on the plural stem (yat/ъ), so
        // it is derived in form(), not article() — see the golden gate.
    }
}
