//! Modern Greek conjugation. Greek is cited (no infinitive) by its 1sg
//! imperfective present. Two things are productive and generated by rule:
//! the -ω-class imperfective present (λύν-ω/-εις/-ει/-ουμε/-ετε/-ουν) and
//! the active present participle / gerund (stem + -οντας). Everything else
//! is lexical and carries a mined row in `data/ell/parts.tsv`: the
//! contracted -άω/-ώ presents, the augmented and stress-shifted imperfect,
//! the perfective past (aorist), and the two imperatives. The synthetic
//! paradigm only — the perfect, future and subjunctive are analytic
//! (έχω/θα/να + form) and out of scope.

use std::collections::HashMap;
use std::sync::OnceLock;

/// The stored cells, in the column order of `data/ell/parts.tsv`.
pub const CELLS: [&str; 21] = [
    "V;1;SG;IPFV;PRS", "V;2;SG;IPFV;PRS", "V;3;SG;IPFV;PRS",
    "V;1;PL;IPFV;PRS", "V;2;PL;IPFV;PRS", "V;3;PL;IPFV;PRS",
    "V;1;SG;IPFV;PST", "V;2;SG;IPFV;PST", "V;3;SG;IPFV;PST",
    "V;1;PL;IPFV;PST", "V;2;PL;IPFV;PST", "V;3;PL;IPFV;PST",
    "V;1;SG;PFV;PST", "V;2;SG;PFV;PST", "V;3;SG;PFV;PST",
    "V;1;PL;PFV;PST", "V;2;PL;PFV;PST", "V;3;PL;PFV;PST",
    "V;2;SG;IMP", "V;2;PL;IMP", "V;PTCP",
];

/// Why a form cannot be produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The input does not look like a Greek 1sg-present citation.
    NotAVerb,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "not a Greek verb")
    }
}

static PARTS_TSV: &str = include_str!("../data/ell/parts.tsv");

fn overrides(cit: &str) -> Option<HashMap<&'static str, &'static str>> {
    static MAP: OnceLock<HashMap<&'static str, HashMap<&'static str, &'static str>>> =
        OnceLock::new();
    let map = MAP.get_or_init(|| {
        let mut m = HashMap::new();
        for line in PARTS_TSV.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let mut cols = line.split('\t');
            let Some(lemma) = cols.next() else { continue };
            let mut row = HashMap::new();
            for (i, val) in cols.enumerate() {
                if val != "-" && !val.is_empty() {
                    if let Some(feat) = CELLS.get(i) {
                        row.insert(*feat, val);
                    }
                }
            }
            m.insert(lemma, row);
        }
        m
    });
    map.get(cit).cloned()
}

/// The productive -ω-class imperfective present and the gerund, or None.
fn productive(cit: &str, feat: &str) -> Option<String> {
    let stem = cit.strip_suffix('ω')?;
    if feat == "V;PTCP" {
        return Some(format!("{stem}οντας"));
    }
    let pn = feat.strip_prefix("V;")?.strip_suffix(";IPFV;PRS")?;
    let end = match pn {
        "1;SG" => "ω",
        "2;SG" => "εις",
        "3;SG" => "ει",
        "1;PL" => "ουμε",
        "2;PL" => "ετε",
        "3;PL" => "ουν",
        _ => return None,
    };
    Some(format!("{stem}{end}"))
}

/// A conjugatable Greek verb, cited by its 1sg imperfective present.
#[derive(Debug, Clone)]
pub struct Verb {
    citation: String,
    overrides: HashMap<&'static str, &'static str>,
}

impl Verb {
    /// Build a verb from its 1sg imperfective-present citation form.
    pub fn from_infinitive(citation: &str) -> Result<Self, Error> {
        let lowered = citation.trim().to_lowercase();
        let cit = if overrides(citation.trim()).is_none() && overrides(&lowered).is_some() {
            lowered.clone()
        } else {
            citation.trim().to_string()
        };
        if cit.is_empty() || cit.contains(char::is_whitespace) {
            return Err(Error::NotAVerb);
        }
        let over = overrides(&cit).unwrap_or_default();
        // Conjugable if stored or an -ω-class present.
        if over.is_empty() && !cit.ends_with('ω') {
            return Err(Error::NotAVerb);
        }
        Ok(Self {
            citation: cit,
            overrides: over,
        })
    }

    /// The citation form (1sg imperfective present).
    pub fn citation(&self) -> &str {
        &self.citation
    }

    /// The form for a UniMorph feature bundle: a mined override if one
    /// exists, else the productive present/gerund rule.
    pub fn form(&self, feature: &str) -> Option<String> {
        if let Some(f) = self.overrides.get(feature) {
            return Some((*f).to_string());
        }
        productive(&self.citation, feature)
    }
}

/// A compact conjugation table — the synthetic paradigm, shared by the
/// WebAssembly and Python bindings.
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct Table {
    /// 1sg imperfective present (the citation).
    pub present: String,
    /// Imperfective present, 1sg/2sg/3sg/1pl/2pl/3pl.
    pub present_all: Vec<Option<String>>,
    /// Imperfect (imperfective past), same order.
    pub imperfect: Vec<Option<String>>,
    /// Aorist (perfective past), same order.
    pub aorist: Vec<Option<String>>,
    /// Imperative 2sg/2pl.
    pub imperative: Vec<Option<String>>,
    /// Active present participle (gerund).
    pub gerund: Option<String>,
}

impl Table {
    #[must_use]
    pub fn build(v: &Verb) -> Self {
        let many = |feats: &[&str]| feats.iter().map(|f| v.form(f)).collect();
        Self {
            present: v.citation().to_string(),
            present_all: many(&[
                "V;1;SG;IPFV;PRS", "V;2;SG;IPFV;PRS", "V;3;SG;IPFV;PRS",
                "V;1;PL;IPFV;PRS", "V;2;PL;IPFV;PRS", "V;3;PL;IPFV;PRS",
            ]),
            imperfect: many(&[
                "V;1;SG;IPFV;PST", "V;2;SG;IPFV;PST", "V;3;SG;IPFV;PST",
                "V;1;PL;IPFV;PST", "V;2;PL;IPFV;PST", "V;3;PL;IPFV;PST",
            ]),
            aorist: many(&[
                "V;1;SG;PFV;PST", "V;2;SG;PFV;PST", "V;3;SG;PFV;PST",
                "V;1;PL;PFV;PST", "V;2;PL;PFV;PST", "V;3;PL;PFV;PST",
            ]),
            imperative: many(&["V;2;SG;IMP", "V;2;PL;IMP"]),
            gerund: v.form("V;PTCP"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(cit: &str) -> Verb {
        Verb::from_infinitive(cit).unwrap()
    }

    #[test]
    fn omega_present_productive() {
        let g = v("γράφω");
        assert_eq!(g.form("V;2;SG;IPFV;PRS").unwrap(), "γράφεις");
        assert_eq!(g.form("V;3;SG;IPFV;PRS").unwrap(), "γράφει");
        assert_eq!(g.form("V;1;PL;IPFV;PRS").unwrap(), "γράφουμε");
        assert_eq!(g.form("V;3;PL;IPFV;PRS").unwrap(), "γράφουν");
        assert_eq!(g.form("V;PTCP").unwrap(), "γράφοντας");
    }
}
