//! Faroese conjugation. Faroese is a West-Nordic (Germanic) language close
//! to Icelandic, cited by its infinitive — overwhelmingly in `-a`. One
//! thing is productive and generated by rule: the regular class-1 weak
//! (`-a` / `-aði`) paradigm. From the infinitive `kasta` the stem is `kast`
//! (drop the final `-a`) and the present-singular stem `psg` additionally
//! drops a `j` in `-ja` verbs (`síggja` → `sígg`):
//!
//! ```text
//!   V;NFIN            = cit                 kasta
//!   V;IND;PRS;1;SG    = psg + i             kasti
//!   V;IND;PRS;2;SG    = stem + ar           kastar
//!   V;IND;PRS;3;SG    = stem + ar           kastar
//!   V;IND;PRS;3 (pl)  = cit                 kasta
//!   V;IND;PST;1..3;SG = stem + aði          kastaði
//!   V;IND;PST;3 (pl)  = stem + aðu          kastaðu
//!   V;IMP;2;SG        = psg                 kast
//!   V;IMP;2;PL        = stem + ið           kastið
//!   V.CVB (supine)    = stem + að           kastað
//!   V.PTCP.PRS        = stem + andi         kastandi
//!   V.PTCP.PST        = stem + aður         kastaður
//! ```
//!
//! Everything else is lexical and carries a mined row in
//! `data/fao/parts.tsv`: the strong verbs (ablaut past, `-in` participle),
//! the other weak classes (`-di`/`-ti`/`-dur` pasts, `-ir`/`-ur` present
//! singulars) and every stem-changing form. Verified against two oracles
//! (UniMorph ∩ kaikki.org), whose overlap is the supine and the past
//! indicative.

use std::collections::HashMap;
use std::sync::OnceLock;

/// The stored cells, in the column order of `data/fao/parts.tsv`. UniMorph
/// syncretises the present/past plural into the numberless `;3` cell.
pub const CELLS: [&str; 14] = [
    "V;NFIN",
    "V;IND;PRS;1;SG",
    "V;IND;PRS;2;SG",
    "V;IND;PRS;3;SG",
    "V;IND;PRS;3",
    "V;IND;PST;1;SG",
    "V;IND;PST;2;SG",
    "V;IND;PST;3;SG",
    "V;IND;PST;3",
    "V;IMP;2;SG",
    "V;IMP;2;PL",
    "V.CVB",
    "V.PTCP.PRS",
    "V.PTCP.PST",
];

/// Why a form cannot be produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The input does not look like a Faroese infinitive.
    NotAVerb,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "not a Faroese infinitive")
    }
}

static PARTS_TSV: &str = include_str!("../data/fao/parts.tsv");

fn overrides(cit: &str) -> Option<HashMap<&'static str, &'static str>> {
    static MAP: OnceLock<HashMap<&'static str, HashMap<&'static str, &'static str>>> =
        OnceLock::new();
    let map = MAP.get_or_init(|| {
        let mut m = HashMap::new();
        for line in PARTS_TSV.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let mut cols = line.split('\t');
            let Some(lemma) = cols.next() else { continue };
            let mut row = HashMap::new();
            for (i, val) in cols.enumerate() {
                if val != "-" && !val.is_empty() {
                    if let Some(feat) = CELLS.get(i) {
                        row.insert(*feat, val);
                    }
                }
            }
            m.insert(lemma, row);
        }
        m
    });
    map.get(cit).cloned()
}

/// The productive class-1 weak form, or None for a non `-a` citation.
/// Mirrors `produce()` in `scripts/fao/mine.py` exactly.
fn productive(cit: &str, feat: &str) -> Option<String> {
    let stem = cit.strip_suffix('a')?;
    // Present-singular stem: `-ja` verbs drop the j (síggja → sígg).
    let psg = stem.strip_suffix('j').unwrap_or(stem);
    Some(match feat {
        "V;NFIN" => cit.to_string(),
        "V;IND;PRS;1;SG" => format!("{psg}i"),
        "V;IND;PRS;2;SG" | "V;IND;PRS;3;SG" => format!("{stem}ar"),
        "V;IND;PRS;3" => cit.to_string(),
        "V;IND;PST;1;SG" | "V;IND;PST;2;SG" | "V;IND;PST;3;SG" => format!("{stem}aði"),
        "V;IND;PST;3" => format!("{stem}aðu"),
        "V;IMP;2;SG" => psg.to_string(),
        "V;IMP;2;PL" => format!("{stem}ið"),
        "V.CVB" => format!("{stem}að"),
        "V.PTCP.PRS" => format!("{stem}andi"),
        "V.PTCP.PST" => format!("{stem}aður"),
        _ => return None,
    })
}

/// A conjugatable Faroese verb, cited by its infinitive.
#[derive(Debug, Clone)]
pub struct Verb {
    citation: String,
    overrides: HashMap<&'static str, &'static str>,
}

impl Verb {
    /// Build a verb from its infinitive (mostly `-a`).
    pub fn from_infinitive(citation: &str) -> Result<Self, Error> {
        let lowered = citation.trim().to_lowercase();
        let cit = if overrides(citation.trim()).is_none() && overrides(&lowered).is_some() {
            lowered.clone()
        } else {
            citation.trim().to_string()
        };
        if cit.is_empty() || cit.contains(char::is_whitespace) {
            return Err(Error::NotAVerb);
        }
        let over = overrides(&cit).unwrap_or_default();
        // Accept a citation only if we can conjugate it: it is either a
        // stored verb or a productive `-a` infinitive.
        if over.is_empty() && !cit.ends_with('a') {
            return Err(Error::NotAVerb);
        }
        Ok(Self {
            citation: cit,
            overrides: over,
        })
    }

    /// The infinitive (citation).
    pub fn citation(&self) -> &str {
        &self.citation
    }

    /// The form for a UniMorph feature bundle: a mined override if one
    /// exists, else the productive weak rule.
    pub fn form(&self, feature: &str) -> Option<String> {
        if let Some(f) = self.overrides.get(feature) {
            return Some((*f).to_string());
        }
        productive(&self.citation, feature)
    }
}

/// A compact conjugation table — the synthetic core, shared by the
/// WebAssembly and Python bindings.
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct Table {
    /// Infinitive (the citation).
    pub infinitive: String,
    /// Present indicative: 1sg / 2sg / 3sg / plural.
    pub present: Vec<Option<String>>,
    /// Past indicative: 1sg / 2sg / 3sg / plural.
    pub past: Vec<Option<String>>,
    /// Imperative 2sg / 2pl.
    pub imperative: Vec<Option<String>>,
    /// Supine (UniMorph `V.CVB`).
    pub supine: Option<String>,
    /// Present participle.
    pub present_participle: Option<String>,
    /// Past participle (masc nom sg).
    pub past_participle: Option<String>,
}

impl Table {
    #[must_use]
    pub fn build(v: &Verb) -> Self {
        let many = |feats: &[&str]| feats.iter().map(|f| v.form(f)).collect();
        Self {
            infinitive: v.citation().to_string(),
            present: many(&[
                "V;IND;PRS;1;SG",
                "V;IND;PRS;2;SG",
                "V;IND;PRS;3;SG",
                "V;IND;PRS;3",
            ]),
            past: many(&[
                "V;IND;PST;1;SG",
                "V;IND;PST;2;SG",
                "V;IND;PST;3;SG",
                "V;IND;PST;3",
            ]),
            imperative: many(&["V;IMP;2;SG", "V;IMP;2;PL"]),
            supine: v.form("V.CVB"),
            present_participle: v.form("V.PTCP.PRS"),
            past_participle: v.form("V.PTCP.PST"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(cit: &str) -> Verb {
        Verb::from_infinitive(cit).unwrap()
    }

    #[test]
    fn regular_weak_present_productive() {
        let k = v("tosa"); // fully regular class-1 weak
        assert_eq!(k.form("V;IND;PRS;1;SG").unwrap(), "tosi");
        assert_eq!(k.form("V;IND;PRS;3;SG").unwrap(), "tosar");
        assert_eq!(k.form("V;IND;PRS;3").unwrap(), "tosa");
        assert_eq!(k.form("V;IND;PST;3;SG").unwrap(), "tosaði");
        assert_eq!(k.form("V;IND;PST;3").unwrap(), "tosaðu");
        assert_eq!(k.form("V;IMP;2;PL").unwrap(), "tosið");
        assert_eq!(k.form("V.CVB").unwrap(), "tosað");
        assert_eq!(k.form("V.PTCP.PRS").unwrap(), "tosandi");
        assert_eq!(k.form("V.PTCP.PST").unwrap(), "tosaður");
    }

    #[test]
    fn ja_verb_present_singular_drops_j() {
        // -ja verbs drop the j in the present-singular stem.
        let s = v("síggja"); // strong verb, but 1sg/plural are productive
        assert_eq!(s.form("V;IND;PRS;1;SG").unwrap(), "síggi");
        assert_eq!(s.form("V;IND;PRS;3").unwrap(), "síggja");
        assert_eq!(s.form("V;NFIN").unwrap(), "síggja");
    }

    #[test]
    fn mined_override_wins() {
        // síggja's strong past is mined, not productive.
        let s = v("síggja");
        assert_eq!(s.form("V;IND;PST;3;SG").unwrap(), "sá");
        assert_eq!(s.form("V.PTCP.PST").unwrap(), "sæddur");
    }
}
