//! Occitan conjugation (Languedocien standard). Occitan is a Romance
//! language cited by its infinitive, with person/number agreement across a
//! rich synthetic paradigm. Two conjugation classes are genuinely
//! productive and generated by rule from the bare stem (the infinitive
//! minus its final two characters):
//!
//!   * the -ar class (parlar → parl-): present -i/-as/-a/-am/-atz/-an,
//!     imperfect -av-, preterite -èr-, future -ar-, conditional -ari-,
//!     present subjunctive -e, imperfect subjunctive -èss-, the three
//!     imperatives, the -at past participle and the -ant gerund;
//!   * the inchoative -ir class (brandir → brand-): the -iss-/-isc-/-iguèr-
//!     augmented paradigm.
//!
//! Everything else — the athematic -er/-re verbs (véser, saber, voler),
//! the short -ir verbs (dormir, venir) and every stem/spelling
//! irregularity of an -ar or -ir verb — carries an explicit form in
//! `data/oci/parts.tsv`, mined from the agreement of the two oracles
//! (UniMorph ∩ kaikki.org). Verified against two oracles.

use std::collections::HashMap;
use std::sync::OnceLock;

/// The stored cells, in the column order of `data/oci/parts.tsv`.
pub const CELLS: [&str; 48] = [
    "V;IND;PRS;1;SG",
    "V;IND;PRS;2;SG",
    "V;IND;PRS;3;SG",
    "V;IND;PRS;1;PL",
    "V;IND;PRS;2;PL",
    "V;IND;PRS;3;PL",
    "V;IND;PST;1;SG;IPFV",
    "V;IND;PST;2;SG;IPFV",
    "V;IND;PST;3;SG;IPFV",
    "V;IND;PST;1;PL;IPFV",
    "V;IND;PST;2;PL;IPFV",
    "V;IND;PST;3;PL;IPFV",
    "V;IND;PST;1;SG;PFV",
    "V;IND;PST;2;SG;PFV",
    "V;IND;PST;3;SG;PFV",
    "V;IND;PST;1;PL;PFV",
    "V;IND;PST;2;PL;PFV",
    "V;IND;PST;3;PL;PFV",
    "V;1;SG;IND;FUT",
    "V;2;SG;IND;FUT",
    "V;3;SG;IND;FUT",
    "V;1;PL;IND;FUT",
    "V;2;PL;IND;FUT",
    "V;3;PL;IND;FUT",
    "V;1;SG;COND",
    "V;2;SG;COND",
    "V;3;SG;COND",
    "V;1;PL;COND",
    "V;2;PL;COND",
    "V;3;PL;COND",
    "V;1;SG;SBJV;PRS",
    "V;2;SG;SBJV;PRS",
    "V;3;SG;SBJV;PRS",
    "V;1;PL;SBJV;PRS",
    "V;2;PL;SBJV;PRS",
    "V;3;PL;SBJV;PRS",
    "V;1;SG;SBJV;PST;IPFV",
    "V;2;SG;SBJV;PST;IPFV",
    "V;3;SG;SBJV;PST;IPFV",
    "V;1;PL;SBJV;PST;IPFV",
    "V;2;PL;SBJV;PST;IPFV",
    "V;3;PL;SBJV;PST;IPFV",
    "V;2;SG;IMP",
    "V;1;PL;IMP",
    "V;2;PL;IMP",
    "V;NFIN",
    "V.PTCP;PST",
    "V.CVB;PRS",
];

/// Why a form cannot be produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The input does not look like an Occitan infinitive.
    NotAVerb,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "not an Occitan infinitive")
    }
}

static PARTS_TSV: &str = include_str!("../data/oci/parts.tsv");

fn overrides(cit: &str) -> Option<HashMap<&'static str, &'static str>> {
    static MAP: OnceLock<HashMap<&'static str, HashMap<&'static str, &'static str>>> =
        OnceLock::new();
    let map = MAP.get_or_init(|| {
        let mut m = HashMap::new();
        for line in PARTS_TSV.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let mut cols = line.split('\t');
            let Some(lemma) = cols.next() else { continue };
            let mut row = HashMap::new();
            for (i, val) in cols.enumerate() {
                if val != "-" && !val.is_empty() {
                    if let Some(feat) = CELLS.get(i) {
                        row.insert(*feat, val);
                    }
                }
            }
            m.insert(lemma, row);
        }
        m
    });
    map.get(cit).cloned()
}

/// The productive ending for the -ar class, keyed by feature bundle.
fn ar_ending(feat: &str) -> Option<&'static str> {
    Some(match feat {
        "V;IND;PRS;1;SG" => "i",
        "V;IND;PRS;2;SG" => "as",
        "V;IND;PRS;3;SG" => "a",
        "V;IND;PRS;1;PL" => "am",
        "V;IND;PRS;2;PL" => "atz",
        "V;IND;PRS;3;PL" => "an",
        "V;IND;PST;1;SG;IPFV" => "avi",
        "V;IND;PST;2;SG;IPFV" => "avas",
        "V;IND;PST;3;SG;IPFV" => "ava",
        "V;IND;PST;1;PL;IPFV" => "àvem",
        "V;IND;PST;2;PL;IPFV" => "àvetz",
        "V;IND;PST;3;PL;IPFV" => "avan",
        "V;IND;PST;1;SG;PFV" => "èri",
        "V;IND;PST;2;SG;PFV" => "ères",
        "V;IND;PST;3;SG;PFV" => "èt",
        "V;IND;PST;1;PL;PFV" => "èrem",
        "V;IND;PST;2;PL;PFV" => "èretz",
        "V;IND;PST;3;PL;PFV" => "èron",
        "V;1;SG;IND;FUT" => "arai",
        "V;2;SG;IND;FUT" => "aràs",
        "V;3;SG;IND;FUT" => "arà",
        "V;1;PL;IND;FUT" => "arem",
        "V;2;PL;IND;FUT" => "aretz",
        "V;3;PL;IND;FUT" => "aràn",
        "V;1;SG;COND" => "ariái",
        "V;2;SG;COND" => "ariás",
        "V;3;SG;COND" => "ariá",
        "V;1;PL;COND" => "ariam",
        "V;2;PL;COND" => "ariatz",
        "V;3;PL;COND" => "arián",
        "V;1;SG;SBJV;PRS" => "e",
        "V;2;SG;SBJV;PRS" => "es",
        "V;3;SG;SBJV;PRS" => "e",
        "V;1;PL;SBJV;PRS" => "em",
        "V;2;PL;SBJV;PRS" => "etz",
        "V;3;PL;SBJV;PRS" => "en",
        "V;1;SG;SBJV;PST;IPFV" => "èssi",
        "V;2;SG;SBJV;PST;IPFV" => "èsses",
        "V;3;SG;SBJV;PST;IPFV" => "èsse",
        "V;1;PL;SBJV;PST;IPFV" => "èssem",
        "V;2;PL;SBJV;PST;IPFV" => "èssetz",
        "V;3;PL;SBJV;PST;IPFV" => "èsson",
        "V;2;SG;IMP" => "a",
        "V;1;PL;IMP" => "em",
        "V;2;PL;IMP" => "atz",
        "V;NFIN" => "ar",
        "V.PTCP;PST" => "at",
        "V.CVB;PRS" => "ant",
        _ => return None,
    })
}

/// The productive ending for the inchoative -ir class, keyed by feature.
fn ir_ending(feat: &str) -> Option<&'static str> {
    Some(match feat {
        "V;IND;PRS;1;SG" => "issi",
        "V;IND;PRS;2;SG" => "isses",
        "V;IND;PRS;3;SG" => "ís",
        "V;IND;PRS;1;PL" => "issèm",
        "V;IND;PRS;2;PL" => "issètz",
        "V;IND;PRS;3;PL" => "isson",
        "V;IND;PST;1;SG;IPFV" => "issiái",
        "V;IND;PST;2;SG;IPFV" => "issiás",
        "V;IND;PST;3;SG;IPFV" => "issiá",
        "V;IND;PST;1;PL;IPFV" => "issiam",
        "V;IND;PST;2;PL;IPFV" => "issiatz",
        "V;IND;PST;3;PL;IPFV" => "issián",
        "V;IND;PST;1;SG;PFV" => "iguèri",
        "V;IND;PST;2;SG;PFV" => "iguères",
        "V;IND;PST;3;SG;PFV" => "iguèt",
        "V;IND;PST;1;PL;PFV" => "iguèrem",
        "V;IND;PST;2;PL;PFV" => "iguèretz",
        "V;IND;PST;3;PL;PFV" => "iguèron",
        "V;1;SG;IND;FUT" => "irai",
        "V;2;SG;IND;FUT" => "iràs",
        "V;3;SG;IND;FUT" => "irà",
        "V;1;PL;IND;FUT" => "irem",
        "V;2;PL;IND;FUT" => "iretz",
        "V;3;PL;IND;FUT" => "iràn",
        "V;1;SG;COND" => "iriái",
        "V;2;SG;COND" => "iriás",
        "V;3;SG;COND" => "iriá",
        "V;1;PL;COND" => "iriam",
        "V;2;PL;COND" => "iriatz",
        "V;3;PL;COND" => "irián",
        "V;1;SG;SBJV;PRS" => "isca",
        "V;2;SG;SBJV;PRS" => "iscas",
        "V;3;SG;SBJV;PRS" => "isca",
        "V;1;PL;SBJV;PRS" => "iscam",
        "V;2;PL;SBJV;PRS" => "iscatz",
        "V;3;PL;SBJV;PRS" => "iscan",
        "V;1;SG;SBJV;PST;IPFV" => "iguèsse",
        "V;2;SG;SBJV;PST;IPFV" => "iguèsses",
        "V;3;SG;SBJV;PST;IPFV" => "iguèsse",
        "V;1;PL;SBJV;PST;IPFV" => "iguèssem",
        "V;2;PL;SBJV;PST;IPFV" => "iguèssetz",
        "V;3;PL;SBJV;PST;IPFV" => "iguèsson",
        "V;2;SG;IMP" => "ís",
        "V;1;PL;IMP" => "iscam",
        "V;2;PL;IMP" => "issetz",
        "V;NFIN" => "ir",
        "V.PTCP;PST" => "it",
        "V.CVB;PRS" => "issent",
        _ => return None,
    })
}

/// The productive form for an -ar or inchoative -ir infinitive, or None for
/// any other citation (athematic -er/-re verbs are entirely mined).
fn productive(cit: &str, feat: &str) -> Option<String> {
    let ending = if cit.ends_with("ar") {
        ar_ending(feat)
    } else if cit.ends_with("ir") {
        ir_ending(feat)
    } else {
        None
    }?;
    // Stem = infinitive minus its final two characters.
    let n = cit.chars().count();
    let stem: String = cit.chars().take(n - 2).collect();
    Some(format!("{stem}{ending}"))
}

/// A conjugatable Occitan verb, cited by its infinitive.
#[derive(Debug, Clone)]
pub struct Verb {
    citation: String,
    overrides: HashMap<&'static str, &'static str>,
}

impl Verb {
    /// Build a verb from its infinitive (e.g. `parlar`, `brandir`,
    /// `véser`).
    pub fn from_infinitive(citation: &str) -> Result<Self, Error> {
        let lowered = citation.trim().to_lowercase();
        let cit = if overrides(citation.trim()).is_none() && overrides(&lowered).is_some() {
            lowered.clone()
        } else {
            citation.trim().to_string()
        };
        if cit.is_empty() || cit.contains(char::is_whitespace) {
            return Err(Error::NotAVerb);
        }
        let over = overrides(&cit).unwrap_or_default();
        // Accept a citation only if it is conjugatable: an -ar / -ir verb
        // driven by the productive rules, or a stored (mined) verb.
        if over.is_empty() && !cit.ends_with("ar") && !cit.ends_with("ir") {
            return Err(Error::NotAVerb);
        }
        Ok(Self {
            citation: cit,
            overrides: over,
        })
    }

    /// The infinitive (citation), as normalized.
    pub fn citation(&self) -> &str {
        &self.citation
    }

    /// The form for a feature bundle: a mined override if one exists, else
    /// the productive -ar / -ir rule. None for unsupported slots.
    pub fn form(&self, feature: &str) -> Option<String> {
        if let Some(f) = self.overrides.get(feature) {
            return Some((*f).to_string());
        }
        productive(&self.citation, feature)
    }
}

/// A compact conjugation table — the synthetic core, shared by the
/// WebAssembly and Python bindings.
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct Table {
    /// Infinitive (the citation).
    pub infinitive: String,
    /// Present indicative, 1sg/2sg/3sg/1pl/2pl/3pl.
    pub present: Vec<Option<String>>,
    /// Imperfect indicative, same order.
    pub imperfect: Vec<Option<String>>,
    /// Preterite (past historic), same order.
    pub preterite: Vec<Option<String>>,
    /// Future, same order.
    pub future: Vec<Option<String>>,
    /// Conditional, same order.
    pub conditional: Vec<Option<String>>,
    /// Present subjunctive, same order.
    pub present_subjunctive: Vec<Option<String>>,
    /// Imperfect subjunctive, same order.
    pub imperfect_subjunctive: Vec<Option<String>>,
    /// Imperative 2sg/1pl/2pl.
    pub imperative: Vec<Option<String>>,
    pub past_participle: Option<String>,
    pub gerund: Option<String>,
}

impl Table {
    #[must_use]
    pub fn build(v: &Verb) -> Self {
        let many = |feats: &[&str]| feats.iter().map(|f| v.form(f)).collect();
        Self {
            infinitive: v.citation().to_string(),
            present: many(&[
                "V;IND;PRS;1;SG",
                "V;IND;PRS;2;SG",
                "V;IND;PRS;3;SG",
                "V;IND;PRS;1;PL",
                "V;IND;PRS;2;PL",
                "V;IND;PRS;3;PL",
            ]),
            imperfect: many(&[
                "V;IND;PST;1;SG;IPFV",
                "V;IND;PST;2;SG;IPFV",
                "V;IND;PST;3;SG;IPFV",
                "V;IND;PST;1;PL;IPFV",
                "V;IND;PST;2;PL;IPFV",
                "V;IND;PST;3;PL;IPFV",
            ]),
            preterite: many(&[
                "V;IND;PST;1;SG;PFV",
                "V;IND;PST;2;SG;PFV",
                "V;IND;PST;3;SG;PFV",
                "V;IND;PST;1;PL;PFV",
                "V;IND;PST;2;PL;PFV",
                "V;IND;PST;3;PL;PFV",
            ]),
            future: many(&[
                "V;1;SG;IND;FUT",
                "V;2;SG;IND;FUT",
                "V;3;SG;IND;FUT",
                "V;1;PL;IND;FUT",
                "V;2;PL;IND;FUT",
                "V;3;PL;IND;FUT",
            ]),
            conditional: many(&[
                "V;1;SG;COND",
                "V;2;SG;COND",
                "V;3;SG;COND",
                "V;1;PL;COND",
                "V;2;PL;COND",
                "V;3;PL;COND",
            ]),
            present_subjunctive: many(&[
                "V;1;SG;SBJV;PRS",
                "V;2;SG;SBJV;PRS",
                "V;3;SG;SBJV;PRS",
                "V;1;PL;SBJV;PRS",
                "V;2;PL;SBJV;PRS",
                "V;3;PL;SBJV;PRS",
            ]),
            imperfect_subjunctive: many(&[
                "V;1;SG;SBJV;PST;IPFV",
                "V;2;SG;SBJV;PST;IPFV",
                "V;3;SG;SBJV;PST;IPFV",
                "V;1;PL;SBJV;PST;IPFV",
                "V;2;PL;SBJV;PST;IPFV",
                "V;3;PL;SBJV;PST;IPFV",
            ]),
            imperative: many(&["V;2;SG;IMP", "V;1;PL;IMP", "V;2;PL;IMP"]),
            past_participle: v.form("V.PTCP;PST"),
            gerund: v.form("V.CVB;PRS"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(cit: &str) -> Verb {
        Verb::from_infinitive(cit).unwrap()
    }

    // The -ar productive paradigm is verified end-to-end by the golden gate
    // against the two-oracle agreement set. A hand-written per-cell test is
    // intentionally omitted here: several -ar cells (e.g. 1SG present, 1PL
    // imperfect) are dialect splits between the oracles and excluded from the
    // gold, so asserting a single norm would be arbitrary.

    #[test]
    fn inchoative_ir_class_productive() {
        let b = v("brandir");
        assert_eq!(b.form("V;IND;PRS;1;SG").unwrap(), "brandissi");
        assert_eq!(b.form("V;IND;PRS;3;SG").unwrap(), "brandís");
        assert_eq!(b.form("V;IND;PST;1;SG;PFV").unwrap(), "brandiguèri");
        assert_eq!(b.form("V;1;SG;SBJV;PRS").unwrap(), "brandisca");
        assert_eq!(b.form("V;2;SG;IMP").unwrap(), "brandís");
        assert_eq!(b.form("V.PTCP;PST").unwrap(), "brandit");
        assert_eq!(b.form("V.CVB;PRS").unwrap(), "brandissent");
    }

    #[test]
    fn irregular_from_mined_data() {
        // véser (to see) is athematic: no productive class, every cell is
        // stored in data/oci/parts.tsv.
        let s = v("véser");
        assert_eq!(s.form("V;IND;PRS;1;SG").unwrap(), "vesi");
        assert_eq!(s.form("V;IND;PRS;3;SG").unwrap(), "ves");
    }
}
