//! Polish conjugation. Polish is cited by its infinitive. Two things are
//! productive and generated by rule: the infinitive itself, and the
//! gendered past l-form, which for the regular -ać/-ić/-yć/-uć verbs is
//! the infinitive minus -ć plus -ł/-ła/-ło (sg masc/fem/neut), -li (virile
//! pl) and -ły (non-virile pl): robić → robił/robiła/robiło/robili/robiły.
//! The class-dependent present, the synthetic (perfective) future and the
//! imperative, together with the irregular pasts (-eć→-ał, -ść, -c stems,
//! suppletives), carry a mined row in `data/pol/parts.tsv`. The
//! periphrastic (imperfective) future and the person-clitic past forms are
//! analytic / UniMorph-only and out of scope.

use std::collections::HashMap;
use std::sync::OnceLock;

/// The stored cells, in the column order of `data/pol/parts.tsv`.
pub const CELLS: [&str; 21] = [
    "V;PRS;1;SG",
    "V;PRS;2;SG",
    "V;PRS;3;SG",
    "V;PRS;1;PL",
    "V;PRS;2;PL",
    "V;PRS;3;PL",
    "V;FUT;1;SG",
    "V;FUT;2;SG",
    "V;FUT;3;SG",
    "V;FUT;1;PL",
    "V;FUT;2;PL",
    "V;FUT;3;PL",
    "V;PST;3;SG;MASC",
    "V;PST;3;SG;FEM",
    "V;PST;3;SG;NEUT",
    "V;PST;3;PL;MASC;HUM",
    "V;PST;3;PL",
    "V;IMP;2;SG",
    "V;IMP;1;PL",
    "V;IMP;2;PL",
    "V;NFIN",
];

/// Why a form cannot be produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The input does not look like a Polish infinitive.
    NotAVerb,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "not a Polish infinitive")
    }
}

static PARTS_TSV: &str = include_str!("../data/pol/parts.tsv");

fn overrides(cit: &str) -> Option<HashMap<&'static str, &'static str>> {
    static MAP: OnceLock<HashMap<&'static str, HashMap<&'static str, &'static str>>> =
        OnceLock::new();
    let map = MAP.get_or_init(|| {
        let mut m = HashMap::new();
        for line in PARTS_TSV.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let mut cols = line.split('\t');
            let Some(lemma) = cols.next() else { continue };
            let mut row = HashMap::new();
            for (i, val) in cols.enumerate() {
                if val != "-" && !val.is_empty() {
                    if let Some(feat) = CELLS.get(i) {
                        row.insert(*feat, val);
                    }
                }
            }
            m.insert(lemma, row);
        }
        m
    });
    map.get(cit).cloned()
}

/// The productive infinitive and regular past l-form, or None.
fn productive(cit: &str, feat: &str) -> Option<String> {
    if feat == "V;NFIN" {
        return Some(cit.to_string());
    }
    let stem = cit.strip_suffix('ć')?;
    let end = match feat {
        "V;PST;3;SG;MASC" => "ł",
        "V;PST;3;SG;FEM" => "ła",
        "V;PST;3;SG;NEUT" => "ło",
        "V;PST;3;PL;MASC;HUM" => "li",
        "V;PST;3;PL" => "ły",
        _ => return None,
    };
    Some(format!("{stem}{end}"))
}

/// A conjugatable Polish verb, cited by its infinitive.
#[derive(Debug, Clone)]
pub struct Verb {
    citation: String,
    overrides: HashMap<&'static str, &'static str>,
}

impl Verb {
    /// Build a verb from its infinitive.
    pub fn from_infinitive(citation: &str) -> Result<Self, Error> {
        let lowered = citation.trim().to_lowercase();
        let cit = if overrides(citation.trim()).is_none() && overrides(&lowered).is_some() {
            lowered.clone()
        } else {
            citation.trim().to_string()
        };
        if cit.is_empty() || cit.contains(char::is_whitespace) {
            return Err(Error::NotAVerb);
        }
        let over = overrides(&cit).unwrap_or_default();
        if over.is_empty() && !cit.ends_with('ć') {
            return Err(Error::NotAVerb);
        }
        Ok(Self {
            citation: cit,
            overrides: over,
        })
    }

    /// The infinitive (citation).
    pub fn citation(&self) -> &str {
        &self.citation
    }

    /// The form for a UniMorph feature bundle: a mined override if one
    /// exists, else the productive infinitive/past rule.
    pub fn form(&self, feature: &str) -> Option<String> {
        if let Some(f) = self.overrides.get(feature) {
            return Some((*f).to_string());
        }
        productive(&self.citation, feature)
    }
}

/// A compact conjugation table — the synthetic paradigm, shared by the
/// WebAssembly and Python bindings.
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct Table {
    /// Infinitive (the citation).
    pub infinitive: String,
    /// Present, 1sg/2sg/3sg/1pl/2pl/3pl (imperfective verbs).
    pub present: Vec<Option<String>>,
    /// Synthetic future, same order (perfective verbs).
    pub future: Vec<Option<String>>,
    /// Past l-form: masc/fem/neut (3sg), virile/non-virile (3pl).
    pub past: Vec<Option<String>>,
    /// Imperative 2sg/1pl/2pl.
    pub imperative: Vec<Option<String>>,
}

impl Table {
    #[must_use]
    pub fn build(v: &Verb) -> Self {
        let many = |feats: &[&str]| feats.iter().map(|f| v.form(f)).collect();
        Self {
            infinitive: v.citation().to_string(),
            present: many(&[
                "V;PRS;1;SG",
                "V;PRS;2;SG",
                "V;PRS;3;SG",
                "V;PRS;1;PL",
                "V;PRS;2;PL",
                "V;PRS;3;PL",
            ]),
            future: many(&[
                "V;FUT;1;SG",
                "V;FUT;2;SG",
                "V;FUT;3;SG",
                "V;FUT;1;PL",
                "V;FUT;2;PL",
                "V;FUT;3;PL",
            ]),
            past: many(&[
                "V;PST;3;SG;MASC",
                "V;PST;3;SG;FEM",
                "V;PST;3;SG;NEUT",
                "V;PST;3;PL;MASC;HUM",
                "V;PST;3;PL",
            ]),
            imperative: many(&["V;IMP;2;SG", "V;IMP;1;PL", "V;IMP;2;PL"]),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(cit: &str) -> Verb {
        Verb::from_infinitive(cit).unwrap()
    }

    #[test]
    fn regular_past_productive() {
        let r = v("robić");
        assert_eq!(r.form("V;NFIN").unwrap(), "robić");
        assert_eq!(r.form("V;PST;3;SG;MASC").unwrap(), "robił");
        assert_eq!(r.form("V;PST;3;SG;FEM").unwrap(), "robiła");
        assert_eq!(r.form("V;PST;3;PL;MASC;HUM").unwrap(), "robili");
        assert_eq!(r.form("V;PST;3;PL").unwrap(), "robiły");
        // present is mined (class-dependent).
        assert_eq!(v("czytać").form("V;PST;3;SG;NEUT").unwrap(), "czytało");
    }
}
