//! Reverse lookup: from a conjugated form back to the infinitive(s).
//!
//! Two complementary mechanisms, both built on the forward engine so a
//! returned analysis is always conjugationally consistent:
//!
//! * **Irregular index** (all 14 languages): on first use, every lemma
//!   in the language's compiled-in exception lexicon is forward-
//!   conjugated and every single-word form is indexed as
//!   `form → (infinitive, slot)`. No new data ships — the index is
//!   derived from the TSVs the crate already embeds.
//! * **Productive de-inflection** (deu, eng, fra, spa): candidate
//!   infinitives are generated by re-segmenting the form (all stem
//!   splits × the language's infinitive endings, plus a few
//!   orthographic mutations such as French è→é and consonant
//!   degemination), then each candidate is forward-conjugated and kept
//!   only if the queried form occurs in its table. Verification means
//!   a match can never cite a slot the engine would not itself produce.
//!
//! Two auxiliary mechanisms extend both paths:
//!
//! * **Prefixed recombination**: when a suffix of the query is an
//!   indexed form of a base verb, the remainder glued onto that base's
//!   infinitive becomes a candidate (*abstiendra* → abs+tenir →
//!   abstenir, *widersprach* → wider+sprechen → widersprechen,
//!   *sunrose* → sun+rise), again subject to forward verification.
//! * **Spelling-variant matching** (deu, eng): the engine emits one
//!   canonical spelling, but the written language allows more; a small
//!   rewrite table bridges them (*meid*/meide, *überträfst*/
//!   überträfest, *verringret*/verringert, British *travelling*).
//!
//! When the form is found in the irregular index, the two classic
//! ghost shapes are suppressed: *suis* is être/suivre, not the
//! hypothetical second-group *\*suir*, and *war* is sein, not the
//! weak *\*waren*.
//!
//! Known limitations (v1):
//! * German separable recombination of free word pairs is out of
//!   scope: *fängt an* (two words) does not reverse; the single-word
//!   spellings *anfängt* (clause-final), *angefangen*, and
//!   *anzufangen* all do.
//! * For forms not covered by the index, the productive path can
//!   return hypothetical lemmas alongside the real one whenever the
//!   surface form is genuinely ambiguous under the engine's own rules
//!   (*vendons* → vendre but also the nonce *\*vender*, which the
//!   engine happily conjugates; *appellerons* → appeler and the
//!   -eller reading). The true lemma is always in the set; index
//!   matches sort first, then shorter candidates.
//! * Multi-word forms (analytic tenses, reflexive clitics) are not
//!   indexed and not de-inflected, and Spanish voseo forms are
//!   excluded from matching.
//! * Only variants the forward engine (plus the rewrite tables) can
//!   produce are found: archaic or regional doublets the engine does
//!   not generate (*schwämme* beside schwömme, English *lit* where
//!   the lexicon holds lighted) do not reverse.

use crate::{conjugate, Conjugation, Lang};
use std::collections::HashMap;
use std::sync::OnceLock;

/// One analysis of a queried form: an infinitive whose paradigm
/// contains the form, plus every slot the form occupies in it.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct ReverseMatch {
    pub infinitive: String,
    /// Slot descriptors like "present 1sg" or "past participle".
    pub slots: Vec<String>,
}

/// Look up a conjugated form: every infinitive whose paradigm contains
/// it, with the slots it fills. Input is trimmed and case-folded like
/// `from_infinitive`. Ambiguous forms return several matches (French
/// *suis* → être and suivre); unknown forms return an empty vector.
#[must_use]
pub fn reverse(form: &str, lang: Lang) -> Vec<ReverseMatch> {
    let query = form.trim().to_lowercase();
    if query.is_empty() || query.contains(char::is_whitespace) {
        return Vec::new();
    }

    // Irregular index first: authoritative for lexicon verbs. French
    // bound stems (-cevoir, -uire) are index-internal: they anchor
    // prefixed recombination below but are not verbs themselves.
    let mut out: Vec<ReverseMatch> = Vec::new();
    if let Some(hits) = index(lang).get(&query) {
        let mut by_lemma: Vec<(String, Vec<String>)> = Vec::new();
        for (inf, slot) in hits {
            if lang == Lang::Fra && FRA_BOUND_STEMS.contains(&inf.as_str()) {
                continue;
            }
            match by_lemma.iter_mut().find(|(l, _)| l == inf) {
                Some((_, slots)) => {
                    if !slots.contains(slot) {
                        slots.push(slot.clone());
                    }
                }
                None => by_lemma.push((inf.clone(), vec![slot.clone()])),
            }
        }
        by_lemma.sort_by(|a, b| a.0.cmp(&b.0));
        out.extend(
            by_lemma
                .into_iter()
                .map(|(infinitive, slots)| ReverseMatch { infinitive, slots }),
        );
    }
    let indexed_hit = !out.is_empty();

    // Prefixed recombination against the index: if a suffix of the
    // query is a known form of an indexed base verb, the prefix glued
    // onto that base's infinitive is a candidate (abstiendra →
    // abs+tenir, widersprach → wider+sprechen, sunrose → sun+rise).
    // Verification below decides whether the engine really supports
    // the prefixed derivative.
    let mut cands = candidates(&query, lang);
    let spellings = if lang == Lang::Deu {
        deu_spellings(&query)
    } else {
        vec![query.clone()]
    };
    for q in &spellings {
        // An alternate spelling may be a known form outright:
        // söfft is the engine's söffet with the schwa dropped.
        if q != &query {
            if let Some(hits) = index(lang).get(q.as_str()) {
                for (inf, _) in hits {
                    if !cands.contains(inf) {
                        cands.push(inf.clone());
                    }
                }
            }
        }
        for (i, _) in q.char_indices().skip(1) {
            let mut push_hits = |key: &str| {
                if let Some(hits) = index(lang).get(key) {
                    for (inf, _) in hits {
                        let cand = format!("{}{inf}", &q[..i]);
                        if !cands.contains(&cand) {
                            cands.push(cand);
                        }
                    }
                }
            };
            push_hits(&q[i..]);
            if lang == Lang::Deu {
                // Inseparable prefixes swallow the participle ge-:
                // entgangen ends in gangen, indexed as gegangen.
                push_hits(&format!("ge{}", &q[i..]));
            }
        }
    }

    // Productive de-inflection: verified candidates. When the form is
    // already claimed by the irregular index, the classic ghost shapes
    // are suppressed (suis must not surface the second-group *suir,
    // war must not surface the weak *waren); other productive readings
    // coexist with the index (gehört is hören's participle and a form
    // of gehören).
    let mut verified: Vec<ReverseMatch> = Vec::new();
    for cand in cands {
        if out.iter().any(|m| m.infinitive == cand) {
            continue; // already found via the index
        }
        if indexed_hit && is_index_shadow(&cand, &query, lang) {
            continue;
        }
        if let Some(m) = verify(&cand, &query, lang) {
            if !verified.iter().any(|v| v.infinitive == m.infinitive) {
                verified.push(m);
            }
        }
    }
    if lang == Lang::Eng && indexed_hit {
        // "went" is a form of go, not the infinitive of *went.
        verified.retain(|m| m.infinitive != query || m.slots.iter().any(|s| s != "infinitive"));
    }

    // Orthographic-twin filter: drop a verified candidate when a more
    // canonical spelling of it (appeller→appeler, cèder→céder,
    // stoppe→stop, studie→study) is itself verified or indexed.
    let keep: Vec<bool> = verified
        .iter()
        .map(|m| {
            !canonical_twins(&m.infinitive, lang).iter().any(|t| {
                t != &m.infinitive
                    && (verified.iter().any(|v| &v.infinitive == t)
                        || out.iter().any(|v| &v.infinitive == t))
            })
        })
        .collect();
    let mut verified: Vec<ReverseMatch> = verified
        .into_iter()
        .zip(keep)
        .filter_map(|(m, k)| k.then_some(m))
        .collect();

    verified.sort_by(|a, b| {
        a.infinitive
            .chars()
            .count()
            .cmp(&b.infinitive.chars().count())
            .then_with(|| a.infinitive.cmp(&b.infinitive))
    });
    out.extend(verified);
    out
}

/// Whether the forward engine itself generates `form` for `lemma`
/// (modulo the same spelling-variant matching `reverse` uses). Test
/// harness support, not public API.
#[doc(hidden)]
#[must_use]
pub fn engine_generates(lemma: &str, form: &str, lang: Lang) -> bool {
    verify(lemma, &form.trim().to_lowercase(), lang).is_some()
}

/// The productive ghost shapes that shadow every irregular form and
/// are only worth suppressing when the index already explains the
/// query: the French second-group reading (any X-is/X-it form yields
/// a hypothetical X-ir) and the German weak verb built on the query
/// itself as a stem (war → *waren). Lexicon lemmas are never ghosts.
fn is_index_shadow(cand: &str, query: &str, lang: Lang) -> bool {
    if is_lexicon_lemma(cand, lang) {
        return false;
    }
    match lang {
        Lang::Fra => cand.ends_with("ir") || cand.ends_with("re"),
        Lang::Deu => cand
            .strip_suffix('n')
            .is_some_and(|b| b == query || b.strip_suffix('e') == Some(query)),
        _ => false,
    }
}

/// Forward-conjugate `cand` and collect the slots where `query`
/// appears. None when the candidate is not a verb shape the engine
/// accepts, or its paradigm does not contain the query.
fn verify(cand: &str, query: &str, lang: Lang) -> Option<ReverseMatch> {
    let mut slots: Vec<String> = Vec::new();
    let mut infinitive = None;
    for (form, slot) in forms_for(cand, lang)? {
        if slot == "infinitive" {
            infinitive = Some(form.clone());
        }
        let form = form.to_lowercase();
        let hit = form == query
            || (lang == Lang::Deu && deu_variant_match(&form, query))
            || (lang == Lang::Eng && eng_variant_match(&form, query));
        if hit && !slots.contains(&slot) {
            slots.push(slot);
        }
    }
    let infinitive = infinitive?;
    // The engine may normalize the candidate (case, zu-stripping); a
    // candidate that normalizes onto a different lemma already in the
    // set would duplicate it, which the caller dedupes by infinitive.
    (!slots.is_empty()).then_some(ReverseMatch { infinitive, slots })
}

/// German spelling variants the engine does not emit but the written
/// language allows: the optional imperative/1sg schwa (meid/meide,
/// dulde/duld), the epenthetic -e- of 2sg/2pl endings (überträfst/
/// überträfest), and the mobile schwa of -eln/-ern stems (heuchle/
/// heuchele, verringert/verringret). A table form matches a query if
/// one rewrite bridges them.
fn deu_variant_match(form: &str, query: &str) -> bool {
    if let Some(b) = form.strip_suffix('e') {
        if b == query {
            return true;
        }
    }
    if query.strip_suffix('e') == Some(form) {
        return true;
    }
    for (a, b) in DEU_REWRITES {
        if let Some(stem) = form.strip_suffix(a) {
            if query.strip_prefix(stem) == Some(b) {
                return true;
            }
        }
    }
    false
}

/// The British doubled-l spelling (travelling, mislabelled) matched
/// against the engine's single-l American forms. Restricted to -ll-
/// after a longer stem so filled does not match file's *filed.
fn eng_variant_match(form: &str, query: &str) -> bool {
    for suf in ["ing", "ed"] {
        if let Some(qstem) = query.strip_suffix(suf) {
            if qstem.ends_with("ll") && qstem.len() >= 6 {
                if let Some(d) = degeminate(qstem) {
                    if format!("{d}{suf}") == form {
                        return true;
                    }
                }
            }
        }
    }
    false
}

/// The spellings a German query might be written in besides its own:
/// the same rewrites, applied to the query. Used to anchor prefixed
/// recombination (vorzögst → vorzögest, whose -zögest tail the index
/// knows as ziehen).
fn deu_spellings(query: &str) -> Vec<String> {
    let mut v = vec![query.to_string()];
    match query.strip_suffix('e') {
        Some(b) => v.push(b.to_string()),
        None => v.push(format!("{query}e")),
    }
    for (a, b) in DEU_REWRITES {
        if let Some(stem) = query.strip_suffix(a) {
            v.push(format!("{stem}{b}"));
        }
    }
    v
}

const DEU_REWRITES: [(&str, &str); 30] = [
    ("est", "st"),
    ("st", "est"),
    ("et", "t"),
    ("t", "et"),
    ("tet", "etet"),
    ("etet", "tet"),
    ("te", "ete"),
    ("ete", "te"),
    ("ten", "eten"),
    ("eten", "ten"),
    ("test", "etest"),
    ("etest", "test"),
    ("elst", "lest"),
    ("lest", "elst"),
    ("ert", "ret"),
    ("ret", "ert"),
    ("elt", "let"),
    ("let", "elt"),
    ("le", "ele"),
    ("ele", "le"),
    ("re", "ere"),
    ("ere", "re"),
    ("re", "er"),
    ("er", "re"),
    ("le", "el"),
    ("el", "le"),
    ("eln", "len"),
    ("ern", "ren"),
    ("erst", "rest"),
    ("rest", "erst"),
];

/// Every single-word form of a lemma with its slot descriptor. For
/// most languages this is the `Table`; French and Spanish also emit
/// spelling variants (payer's *paye*, the Spanish -se subjunctive,
/// the 1990 French grave-accent future), and Irish emits the bare
/// analytic bases (chuaigh) that the display table only shows glued
/// to a pronoun.
fn forms_for(lemma: &str, lang: Lang) -> Option<Vec<(String, String)>> {
    match lang {
        Lang::Fra => fra_forms(lemma),
        Lang::Spa => spa_forms(lemma),
        Lang::Gle => gle_forms(lemma),
        Lang::Deu => deu_forms(lemma),
        _ => conjugate(lemma, lang).ok().map(|t| enumerate(&t)),
    }
}

/// German forms, with the clause-final spelling of separable verbs
/// joined back on: the table renders "dankten ab", but in subordinate
/// clauses the same slot is written *abdankten*, and that is the form
/// corpora index. Two-word forms whose second word is the verb's own
/// leading particle are re-joined; live recombination of free-standing
/// "fängt ... an" word pairs stays out of scope.
fn deu_forms(lemma: &str) -> Option<Vec<(String, String)>> {
    let table = conjugate(lemma, Lang::Deu).ok()?;
    let Conjugation::Deu(t) = &table else {
        unreachable!()
    };
    let infinitive = t.infinitive.clone();
    let mut forms = enumerate(&table);
    let mut joined: Vec<(String, String)> = Vec::new();
    let mut join = |row: &[String], tense: &str, labels: &[&str]| {
        for (f, l) in row.iter().zip(labels) {
            if let Some((verb, particle)) = f.split_once(' ') {
                if !particle.contains(' ') && infinitive.starts_with(particle) {
                    joined.push((
                        format!("{particle}{verb}"),
                        format!("{tense} {l} (clause-final)"),
                    ));
                }
            }
        }
    };
    join(&t.present, "present", &P6);
    join(&t.preterite, "preterite", &P6);
    join(&t.konjunktiv1, "konjunktiv i", &P6);
    join(&t.konjunktiv2, "konjunktiv ii", &P6);
    forms.append(&mut joined);
    Some(forms)
}

fn fra_forms(lemma: &str) -> Option<Vec<(String, String)>> {
    use crate::fra::{Number, Person, SimpleTense, Verb};
    let v = Verb::from_infinitive(lemma).ok()?;
    let mut s = Slots(Vec::new());
    s.one(&v.infinitive(), "infinitive");
    for f in v.present_participle_variants() {
        s.one(&f, "present participle");
    }
    // The agreeing participle forms (allée, vendus, mises): fem +e,
    // pl +s (masc pl unchanged after -s/-x).
    let pp = v.past_participle();
    s.one(&pp, "past participle");
    if !pp.ends_with('s') && !pp.ends_with('x') {
        s.one(&format!("{pp}s"), "past participle masc pl");
    }
    s.one(&format!("{pp}e"), "past participle fem sg");
    s.one(&format!("{pp}es"), "past participle fem pl");
    let persons = [
        (Person::First, Number::Singular, "1sg"),
        (Person::Second, Number::Singular, "2sg"),
        (Person::Third, Number::Singular, "3sg"),
        (Person::First, Number::Plural, "1pl"),
        (Person::Second, Number::Plural, "2pl"),
        (Person::Third, Number::Plural, "3pl"),
    ];
    for (p, n, l) in [
        (Person::Second, Number::Singular, "2sg"),
        (Person::First, Number::Plural, "1pl"),
        (Person::Second, Number::Plural, "2pl"),
    ] {
        for f in v.imperative_variants(p, n) {
            s.one(&f, &format!("imperative {l}"));
        }
    }
    for (t, name) in [
        (SimpleTense::Present, "present"),
        (SimpleTense::Imperfect, "imperfect"),
        (SimpleTense::PastHistoric, "past historic"),
        (SimpleTense::Future, "future"),
        (SimpleTense::Conditional, "conditional"),
        (SimpleTense::SubjunctivePresent, "subjunctive present"),
        (SimpleTense::SubjunctiveImperfect, "subjunctive imperfect"),
    ] {
        for (p, n, l) in persons {
            for f in v.variants(t, p, n) {
                s.one(&f, &format!("{name} {l}"));
            }
        }
    }
    Some(s.0)
}

fn spa_forms(lemma: &str) -> Option<Vec<(String, String)>> {
    use crate::spa::{Number, Person, SimpleTense, Verb};
    let v = Verb::from_infinitive(lemma).ok()?;
    let mut s = Slots(Vec::new());
    s.one(&v.infinitive(), "infinitive");
    s.one(&v.gerund(), "gerund");
    for (fem, pl, l) in [
        (false, false, "masc sg"),
        (true, false, "fem sg"),
        (false, true, "masc pl"),
        (true, true, "fem pl"),
    ] {
        s.one(
            &v.past_participle_inflected(fem, pl),
            &format!("past participle {l}"),
        );
    }
    let persons = [
        (Person::First, Number::Singular, "1sg"),
        (Person::Second, Number::Singular, "2sg"),
        (Person::Third, Number::Singular, "3sg"),
        (Person::First, Number::Plural, "1pl"),
        (Person::Second, Number::Plural, "2pl"),
        (Person::Third, Number::Plural, "3pl"),
    ];
    for (p, n, l) in [
        (Person::Second, Number::Singular, "tú"),
        (Person::Third, Number::Singular, "usted"),
        (Person::First, Number::Plural, "nosotros"),
        (Person::Second, Number::Plural, "vosotros"),
        (Person::Third, Number::Plural, "ustedes"),
    ] {
        if let Some(f) = v.imperative(p, n) {
            s.one(&f, &format!("imperative {l}"));
        }
    }
    for (t, name) in [
        (SimpleTense::Present, "present"),
        (SimpleTense::Imperfect, "imperfect"),
        (SimpleTense::Preterite, "preterite"),
        (SimpleTense::Future, "future"),
        (SimpleTense::Conditional, "conditional"),
        (SimpleTense::SubjunctivePresent, "subjunctive present"),
        (SimpleTense::SubjunctiveImperfect, "subjunctive imperfect"),
        (SimpleTense::SubjunctiveFuture, "subjunctive future"),
    ] {
        for (p, n, l) in persons {
            for f in v.variants(t, p, n) {
                s.one(&f, &format!("{name} {l}"));
            }
        }
    }
    Some(s.0)
}

fn gle_forms(lemma: &str) -> Option<Vec<(String, String)>> {
    use crate::gle::{Slot, Tense, Verb};
    let v = Verb::from_infinitive(lemma).ok()?;
    let mut s = Slots(Vec::new());
    s.one(v.infinitive(), "infinitive");
    s.one(&v.verbal_noun(), "verbal noun");
    s.one(&v.verbal_adjective(), "verbal adjective");
    for (t, name) in [
        (Tense::Present, "present"),
        (Tense::Past, "past"),
        (Tense::PastHabitual, "past habitual"),
        (Tense::Future, "future"),
        (Tense::Conditional, "conditional"),
        (Tense::Imperative, "imperative"),
        (Tense::Subjunctive, "subjunctive"),
    ] {
        // The written standard lenites past/habitual/conditional forms
        // (téigh → chuaigh); the autonomous is lenited only in the
        // habitual and conditional. Mirrors gle::Table::row.
        let mutate = matches!(t, Tense::Past | Tense::PastHabitual | Tense::Conditional);
        let mutate_auto = matches!(t, Tense::PastHabitual | Tense::Conditional);
        for (slot, l) in [
            (Slot::Base, ""),
            (Slot::FirstSingular, " 1sg"),
            (Slot::SecondSingular, " 2sg"),
            (Slot::FirstPlural, " 1pl"),
            (Slot::SecondPlural, " 2pl"),
            (Slot::ThirdPlural, " 3pl"),
            (Slot::Autonomous, " autonomous"),
        ] {
            if let Some(f) = v.form(t, slot) {
                let f = if (mutate && slot != Slot::Autonomous)
                    || (mutate_auto && slot == Slot::Autonomous)
                {
                    Verb::lenite(&f)
                } else {
                    f
                };
                s.one(&f, &format!("{name}{l}"));
            }
        }
    }
    Some(s.0)
}

// ---------------------------------------------------------------------
// Candidate generation (productive languages only).
// ---------------------------------------------------------------------

const FR_VOWELS: &str = "aeiouyàâéèêëîïôûü";

/// Candidate infinitives for the productive de-inflection path.
/// Over-generation is fine — every candidate is verified by forward
/// conjugation — so the generators favour recall over precision.
fn candidates(query: &str, lang: Lang) -> Vec<String> {
    let mut set: Vec<String> = Vec::new();
    let mut push = |s: String| {
        if !set.contains(&s) {
            set.push(s);
        }
    };
    let prefixes = |s: &str| -> Vec<String> {
        s.char_indices()
            .skip(1)
            .map(|(i, _)| s[..i].to_string())
            .chain(std::iter::once(s.to_string()))
            .collect()
    };
    match lang {
        Lang::Fra => {
            let mut stems = prefixes(query);
            for stem in prefixes(query) {
                // appell → appel (consonant degemination).
                if let Some(d) = degeminate(&stem) {
                    stems.push(d);
                }
                // lèv → lev / léd → cèd → céd (1990 and classic grave).
                if let Some(i) = stem.rfind('è') {
                    stems.push(format!("{}é{}", &stem[..i], &stem[i + "è".len()..]));
                    stems.push(format!("{}e{}", &stem[..i], &stem[i + "è".len()..]));
                }
                // pai → pay, essui → essuy (y-stem verbs).
                if let Some(base) = stem.strip_suffix('i') {
                    if base.chars().last().is_some_and(|c| FR_VOWELS.contains(c)) {
                        stems.push(format!("{base}y"));
                    }
                }
                // annonç → annonc (cedilla before a/o endings).
                if let Some(base) = stem.strip_suffix('ç') {
                    stems.push(format!("{base}c"));
                }
            }
            for stem in stems {
                for end in ["er", "ir", "re"] {
                    push(format!("{stem}{end}"));
                }
            }
        }
        Lang::Spa => {
            let mut stems = prefixes(query);
            for stem in prefixes(query) {
                // Diphthong and vowel alternations back to the lemma
                // vowel: cuent → cont/cunt, quier → quer, pid → ped.
                for (from, tos) in [("ue", &["o", "u"][..]), ("ie", &["e", "i"]), ("i", &["e"])] {
                    if let Some(i) = stem.rfind(from) {
                        for to in tos {
                            stems.push(format!("{}{to}{}", &stem[..i], &stem[i + from.len()..]));
                        }
                    }
                }
                // Orthographic stem-final alternations: saqu → sac,
                // llegu → lleg, empec → empez, coj → cog, averigü →
                // averigu, conozc → conoc, arguy → argü.
                for (suf, to) in [
                    ("qu", "c"),
                    ("gu", "g"),
                    ("c", "z"),
                    ("j", "g"),
                    ("gü", "gu"),
                    ("zc", "c"),
                    ("uy", "ü"),
                ] {
                    if let Some(base) = stem.strip_suffix(suf) {
                        stems.push(format!("{base}{to}"));
                    }
                }
            }
            for stem in stems {
                for end in ["ar", "er", "ir"] {
                    push(format!("{stem}{end}"));
                }
            }
            // Strong participle families whose stem reshapes the whole
            // ending: abierto→abrir, inscrita→inscribir,
            // devuelto→devolver (with gender/number agreement).
            let bare = query.strip_suffix('s').unwrap_or(query);
            let bare = match bare.strip_suffix('a') {
                Some(b) => format!("{b}o"),
                None => bare.to_string(),
            };
            for (pat, repl) in [("ierto", "rir"), ("crito", "cribir"), ("uelto", "olver")] {
                if let Some(base) = bare.strip_suffix(pat) {
                    push(format!("{base}{repl}"));
                }
            }
        }
        Lang::Deu => {
            // Besides plain re-segmentation, drop a "ge" (participle:
            // gekauft → kauft*, angefangen → anfangen) or a "zu"
            // (anzufangen → anfangen) anywhere in the form.
            let mut bases = vec![query.to_string()];
            for infix in ["ge", "zu"] {
                let mut at = 0;
                while let Some(i) = query[at..].find(infix) {
                    let i = at + i;
                    bases.push(format!("{}{}", &query[..i], &query[i + infix.len()..]));
                    at = i + infix.len();
                }
            }
            for base in bases {
                let mut stems = prefixes(&base);
                // Umlauted present (stößt) and Konjunktiv II (käme)
                // stems back to the lemma vowel.
                for stem in prefixes(&base) {
                    for (from, to) in [("äu", "au"), ("ä", "a"), ("ö", "o"), ("ü", "u")] {
                        if let Some(i) = stem.rfind(from) {
                            stems.push(format!("{}{to}{}", &stem[..i], &stem[i + from.len()..]));
                        }
                    }
                    // Mobile schwa of -eln/-ern verbs: the elided stem
                    // (rumkümml-, verringr-, abmeir-) back to the
                    // lemma shape.
                    if stem.ends_with(['l', 'r']) && stem.chars().count() >= 3 {
                        let cut = stem.len() - 1;
                        stems.push(format!("{}e{}", &stem[..cut], &stem[cut..]));
                    }
                }
                for stem in stems {
                    push(format!("{stem}en"));
                    push(format!("{stem}n"));
                }
            }
        }
        Lang::Eng => {
            let mut stems = prefixes(query);
            for stem in prefixes(query) {
                if let Some(d) = degeminate(&stem) {
                    stems.push(d); // stopp → stop
                }
                if let Some(base) = stem.strip_suffix('i') {
                    stems.push(format!("{base}y")); // tri → try
                }
            }
            for stem in stems {
                push(stem.clone());
                push(format!("{stem}e"));
            }
        }
        _ => {}
    }
    set
}

/// Undouble a stem-final geminate consonant (appell → appel).
fn degeminate(stem: &str) -> Option<String> {
    let mut chars = stem.chars();
    let last = chars.next_back()?;
    let prev = chars.next_back()?;
    (last == prev && last.is_alphabetic() && !"aeiouyàâéèêëîïôûü".contains(last))
        .then(|| stem[..stem.len() - last.len_utf8()].to_string())
}

/// More canonical spellings of a candidate infinitive: if one of these
/// is itself a verified match, the candidate is an orthographic ghost
/// of it (appeller of appeler, cèder of céder, stoppe of stop) and is
/// dropped. Deliberately narrow — real doublets stay untouched.
/// Only French has twins worth filtering. There is deliberately no
/// degemination twin (for "appellerons" both appeler and an -eller
/// reading genuinely exist in French orthography), and English is left
/// unfiltered: for "advised" both advise and the nonce *advis verify,
/// and no orthographic rule can pick one without claiming the other
/// direction for "stopped" (stop vs *stoppe).
fn canonical_twins(cand: &str, lang: Lang) -> Vec<String> {
    let mut twins = Vec::new();
    if lang == Lang::Fra {
        for end in ["er", "ir", "re"] {
            if let Some(stem) = cand.strip_suffix(end) {
                if let Some(base) = stem.strip_suffix('i') {
                    if base.chars().last().is_some_and(|c| FR_VOWELS.contains(c)) {
                        twins.push(format!("{base}y{end}")); // paier → payer
                    }
                }
            }
        }
        if let Some(i) = cand.rfind('è') {
            // cèder → céder / lèver → lever.
            twins.push(format!("{}é{}", &cand[..i], &cand[i + "è".len()..]));
            twins.push(format!("{}e{}", &cand[..i], &cand[i + "è".len()..]));
        }
    }
    twins
}

// ---------------------------------------------------------------------
// The irregular index.
// ---------------------------------------------------------------------

type Index = HashMap<String, Vec<(String, String)>>;

fn ord(lang: Lang) -> usize {
    match lang {
        Lang::Deu => 0,
        Lang::Ces => 1,
        Lang::Dan => 2,
        Lang::Eng => 3,
        Lang::Est => 4,
        Lang::Fin => 5,
        Lang::Fra => 6,
        Lang::Slv => 7,
        Lang::Spa => 8,
        Lang::Por => 9,
        Lang::Gle => 10,
        Lang::Ita => 11,
        Lang::Ron => 12,
        Lang::Swe => 13,
        Lang::Cat => 14,
        Lang::Ukr => 15,
        Lang::Isl => 16,
    }
}

fn index(lang: Lang) -> &'static Index {
    #[allow(clippy::declare_interior_mutable_const)]
    const EMPTY: OnceLock<Index> = OnceLock::new();
    static INDEXES: [OnceLock<Index>; 17] = [EMPTY; 17];
    INDEXES[ord(lang)].get_or_init(|| build_index(lang))
}

fn build_index(lang: Lang) -> Index {
    let mut idx: Index = HashMap::new();
    for lemma in lexicon_lemmas(lang) {
        let Some(forms) = forms_for(lemma, lang) else {
            continue;
        };
        let mut infinitive = lemma.to_string();
        for (form, slot) in &forms {
            if slot == "infinitive" {
                infinitive.clone_from(form);
            }
        }
        for (form, slot) in forms {
            let entry = idx.entry(form.to_lowercase()).or_default();
            let pair = (infinitive.clone(), slot);
            if !entry.contains(&pair) {
                entry.push(pair);
            }
        }
    }
    idx
}

fn is_lexicon_lemma(cand: &str, lang: Lang) -> bool {
    #[allow(clippy::declare_interior_mutable_const)]
    const EMPTY: OnceLock<std::collections::HashSet<&'static str>> = OnceLock::new();
    static SETS: [OnceLock<std::collections::HashSet<&'static str>>; 17] = [EMPTY; 17];
    SETS[ord(lang)]
        .get_or_init(|| lexicon_lemmas(lang).into_iter().collect())
        .contains(cand)
}

/// French lexicon rows that are bound stems, not verbs (conduire's
/// -uire, écrire's -crire): excluded from the index so they never
/// surface as infinitives.
const FRA_BOUND_STEMS: [&str; 7] = [
    "crire", "uire", "clure", "cevoir", "eindre", "oindre", "aindre",
];

/// The lemma column of every lexicon TSV the language module already
/// embeds. These are exactly the verbs with non-productive morphology
/// (plus, for some languages, class or auxiliary listings — harmless
/// extra coverage).
fn lexicon_lemmas(lang: Lang) -> Vec<&'static str> {
    fn col1(tsv: &'static str, out: &mut Vec<&'static str>) {
        for line in tsv.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let lemma = line.split('\t').next().unwrap_or("").trim();
            if !lemma.is_empty()
                && !lemma.contains(char::is_whitespace)
                && !lemma.contains(['\'', '\u{2019}'])
            {
                out.push(lemma);
            }
        }
    }
    let mut lemmas = Vec::new();
    match lang {
        Lang::Deu => {
            col1(include_str!("../data/deu/verbs.tsv"), &mut lemmas);
            // The stored suppletives live in code, not in the TSV.
            lemmas.extend(["sein", "werden", "tun"]);
        }
        Lang::Ces => {
            col1(include_str!("../data/ces/verbs.tsv"), &mut lemmas);
            col1(include_str!("../data/ces/classes.tsv"), &mut lemmas);
            col1(include_str!("../data/ces/aspect.tsv"), &mut lemmas);
        }
        Lang::Dan => {
            col1(include_str!("../data/dan/parts.tsv"), &mut lemmas);
            col1(include_str!("../data/dan/auxiliaries.tsv"), &mut lemmas);
        }
        Lang::Eng => col1(include_str!("../data/eng/verbs.tsv"), &mut lemmas),
        Lang::Est => col1(include_str!("../data/est/verbs.tsv"), &mut lemmas),
        Lang::Fin => col1(include_str!("../data/fin/verbs.tsv"), &mut lemmas),
        // Bound stems stay in: their indexed forms anchor prefixed
        // recombination (apercevais → aper+cevoir → apercevoir); the
        // direct lookup filters them out of results.
        Lang::Fra => col1(include_str!("../data/fra/verbs.tsv"), &mut lemmas),
        Lang::Slv => {
            col1(include_str!("../data/slv/verbs.tsv"), &mut lemmas);
            col1(include_str!("../data/slv/classes.tsv"), &mut lemmas);
        }
        Lang::Spa => {
            col1(include_str!("../data/spa/verbs.tsv"), &mut lemmas);
            col1(include_str!("../data/spa/classes.tsv"), &mut lemmas);
        }
        Lang::Por => {
            col1(include_str!("../data/por/verbs.tsv"), &mut lemmas);
            col1(include_str!("../data/por/classes.tsv"), &mut lemmas);
        }
        Lang::Gle => col1(include_str!("../data/gle/verbs.tsv"), &mut lemmas),
        Lang::Ita => {
            col1(include_str!("../data/ita/verbs.tsv"), &mut lemmas);
            col1(include_str!("../data/ita/strong.tsv"), &mut lemmas);
            col1(include_str!("../data/ita/classes.tsv"), &mut lemmas);
            col1(include_str!("../data/ita/auxiliaries.tsv"), &mut lemmas);
        }
        Lang::Ron => {
            col1(include_str!("../data/ron/verbs.tsv"), &mut lemmas);
            col1(include_str!("../data/ron/classes.tsv"), &mut lemmas);
        }
        Lang::Swe => col1(include_str!("../data/swe/parts.tsv"), &mut lemmas),
        Lang::Cat => col1(include_str!("../data/cat/verbs.tsv"), &mut lemmas),
        Lang::Ukr => col1(include_str!("../data/ukr/verbs.tsv"), &mut lemmas),
        Lang::Isl => col1(include_str!("../data/isl/verbs.tsv"), &mut lemmas),
    }
    lemmas.sort_unstable();
    lemmas.dedup();
    lemmas
}

// ---------------------------------------------------------------------
// Slot enumeration: every single-word form of a table with its name.
// ---------------------------------------------------------------------

const P6: [&str; 6] = ["1sg", "2sg", "3sg", "1pl", "2pl", "3pl"];
const P9: [&str; 9] = [
    "1sg", "2sg", "3sg", "1du", "2du", "3du", "1pl", "2pl", "3pl",
];
const P7: [&str; 7] = ["1sg", "2sg", "3sg", "1pl", "2pl", "3pl", "autonomous"];

struct Slots(Vec<(String, String)>);

impl Slots {
    fn one(&mut self, form: &str, name: &str) {
        if !form.is_empty()
            && form != "-"
            && form != "\u{2014}"
            && !form.contains(char::is_whitespace)
        {
            self.0.push((form.to_string(), name.to_string()));
        }
    }
    fn opt(&mut self, form: Option<&String>, name: &str) {
        if let Some(f) = form {
            self.one(f, name);
        }
    }
    fn row(&mut self, forms: &[String], tense: &str, labels: &[&str]) {
        for (f, l) in forms.iter().zip(labels) {
            self.one(f, &format!("{tense} {l}"));
        }
    }
    fn row_opt(&mut self, forms: &[Option<String>], tense: &str, labels: &[&str]) {
        for (f, l) in forms.iter().zip(labels) {
            self.opt(f.as_ref(), &format!("{tense} {l}"));
        }
    }
}

/// Enumerate the synthetic, single-word forms of a table with slot
/// descriptors. Analytic tenses and auxiliary listings are skipped: an
/// auxiliary is not a form of the verb, and analytic forms are
/// multi-word. The infinitive slot is always named "infinitive".
#[allow(clippy::too_many_lines)]
fn enumerate(c: &Conjugation) -> Vec<(String, String)> {
    let mut s = Slots(Vec::new());
    match c {
        Conjugation::Deu(t) => {
            s.one(&t.infinitive, "infinitive");
            s.one(&t.zu_infinitive, "zu-infinitive");
            s.one(&t.present_participle, "present participle");
            s.one(&t.past_participle, "past participle");
            s.row_opt(&t.imperative, "imperative", &["2sg", "2pl"]);
            s.row(&t.present, "present", &P6);
            s.row(&t.preterite, "preterite", &P6);
            s.row(&t.konjunktiv1, "konjunktiv i", &P6);
            s.row(&t.konjunktiv2, "konjunktiv ii", &P6);
        }
        Conjugation::Ces(t) => {
            s.one(&t.infinitive, "infinitive");
            s.row(&t.present, "present", &P6);
            s.row_opt(&t.imperative, "imperative", &["2sg", "1pl", "2pl"]);
            let part = [
                "masc sg", "fem sg", "neut sg", "masc pl", "fem pl", "neut pl",
            ];
            s.row(&t.past_participle, "past participle", &part);
            if let Some(p) = &t.passive_participle {
                s.row(p, "passive participle", &part);
            }
            s.row_opt(
                &t.transgressive,
                "transgressive",
                &["masc", "fem/neut", "pl"],
            );
        }
        Conjugation::Dan(t) => {
            s.one(&t.infinitive, "infinitive");
            s.opt(t.present.as_ref(), "present");
            s.opt(t.past.as_ref(), "past");
            s.opt(t.past_participle.as_ref(), "past participle");
            s.opt(t.imperative.as_ref(), "imperative");
            s.opt(t.present_participle.as_ref(), "present participle");
            s.opt(t.infinitive_passive.as_ref(), "passive infinitive");
            s.opt(t.present_passive.as_ref(), "passive present");
            s.opt(t.past_passive.as_ref(), "passive past");
        }
        Conjugation::Eng(t) => {
            s.one(&t.infinitive, "infinitive");
            s.one(&t.past, "past");
            s.one(&t.past_participle, "past participle");
            s.one(&t.present_participle, "present participle");
            s.one(&t.third_singular, "present 3sg");
        }
        Conjugation::Est(t) => {
            s.one(&t.infinitive, "infinitive");
            s.one(&t.da_infinitive, "da-infinitive");
            s.row(&t.present, "present", &P6);
            s.row(&t.past, "past", &P6);
            s.row(&t.conditional, "conditional", &P6);
            s.row_opt(&t.imperative, "imperative", &["2sg", "3sg", "1pl", "2pl"]);
            s.one(&t.present_impersonal, "impersonal present");
            s.one(&t.past_impersonal, "impersonal past");
            s.one(&t.quotative, "quotative");
            s.one(&t.present_participle, "present participle");
            s.one(&t.nud_participle, "nud-participle");
            s.one(&t.tud_participle, "tud-participle");
        }
        Conjugation::Fin(t) => {
            s.one(&t.infinitive, "infinitive");
            s.row(&t.present, "present", &P6);
            s.row(&t.past, "past", &P6);
            s.row(&t.conditional, "conditional", &P6);
            s.row(&t.potential, "potential", &P6);
            s.row_opt(
                &t.imperative,
                "imperative",
                &["2sg", "3sg", "1pl", "2pl", "3pl"],
            );
            s.one(&t.present_passive, "passive present");
            s.one(&t.past_passive, "passive past");
            s.one(&t.conditional_passive, "passive conditional");
            s.one(&t.potential_passive, "passive potential");
            s.one(&t.imperative_passive, "passive imperative");
            s.one(&t.present_participle, "present participle");
            s.one(&t.past_participle, "past participle");
            s.one(&t.present_passive_participle, "passive present participle");
            s.one(&t.past_passive_participle, "passive past participle");
        }
        Conjugation::Fra(t) => {
            s.one(&t.infinitive, "infinitive");
            s.one(&t.present_participle, "present participle");
            s.one(&t.past_participle, "past participle");
            s.row_opt(&t.imperative, "imperative", &["2sg", "1pl", "2pl"]);
            s.row(&t.present, "present", &P6);
            s.row(&t.imperfect, "imperfect", &P6);
            s.row(&t.past_historic, "past historic", &P6);
            s.row(&t.future, "future", &P6);
            s.row(&t.conditional, "conditional", &P6);
            s.row(&t.subjunctive_present, "subjunctive present", &P6);
            s.row(&t.subjunctive_imperfect, "subjunctive imperfect", &P6);
        }
        Conjugation::Gle(t) => {
            s.one(&t.lemma, "infinitive");
            s.one(&t.verbal_noun, "verbal noun");
            s.one(&t.verbal_adjective, "verbal adjective");
            s.row_opt(&t.present, "present", &P7);
            s.row_opt(&t.past, "past", &P7);
            s.row_opt(&t.past_habitual, "past habitual", &P7);
            s.row_opt(&t.future, "future", &P7);
            s.row_opt(&t.conditional, "conditional", &P7);
            s.row_opt(&t.imperative, "imperative", &P7);
            s.row_opt(&t.subjunctive, "subjunctive", &P7);
        }
        Conjugation::Ita(t) => {
            s.one(&t.infinitive, "infinitive");
            s.one(&t.gerund, "gerund");
            s.one(&t.present_participle, "present participle");
            s.one(&t.past_participle, "past participle");
            s.row_opt(
                &t.imperative,
                "imperative",
                &["tu", "lei", "noi", "voi", "loro"],
            );
            s.row(&t.present, "present", &P6);
            s.row(&t.imperfect, "imperfect", &P6);
            s.row(&t.past_historic, "past historic", &P6);
            s.row(&t.future, "future", &P6);
            s.row(&t.conditional, "conditional", &P6);
            s.row(&t.subjunctive_present, "subjunctive present", &P6);
            s.row(&t.subjunctive_imperfect, "subjunctive imperfect", &P6);
        }
        Conjugation::Por(t) => {
            s.one(&t.infinitive, "infinitive");
            s.one(&t.gerund, "gerund");
            s.one(&t.past_participle, "past participle");
            s.row_opt(
                &t.imperative,
                "imperative",
                &["tu", "você", "nós", "vós", "vocês"],
            );
            s.row(&t.personal_infinitive, "personal infinitive", &P6);
            s.row(&t.present, "present", &P6);
            s.row(&t.imperfect, "imperfect", &P6);
            s.row(&t.preterite, "preterite", &P6);
            s.row(&t.pluperfect, "pluperfect", &P6);
            s.row(&t.future, "future", &P6);
            s.row(&t.conditional, "conditional", &P6);
            s.row(&t.subjunctive_present, "subjunctive present", &P6);
            s.row(&t.subjunctive_imperfect, "subjunctive imperfect", &P6);
            s.row(&t.subjunctive_future, "subjunctive future", &P6);
        }
        Conjugation::Ron(t) => {
            s.one(&t.infinitive, "infinitive");
            s.one(&t.gerund, "gerund");
            s.one(&t.participle, "participle");
            s.row(&t.imperative, "imperative", &["2sg", "2pl"]);
            s.row(&t.present, "present", &P6);
            s.row(&t.imperfect, "imperfect", &P6);
            s.row(&t.simple_perfect, "simple perfect", &P6);
            s.row(&t.pluperfect, "pluperfect", &P6);
            s.row(&t.subjunctive, "subjunctive", &P6);
        }
        Conjugation::Slv(t) => {
            s.one(&t.infinitive, "infinitive");
            s.one(&t.supine, "supine");
            s.row(&t.present, "present", &P9);
            s.row_opt(
                &t.imperative,
                "imperative",
                &["2sg", "1du", "2du", "1pl", "2pl"],
            );
            s.row(
                &t.participle,
                "l-participle",
                &[
                    "masc sg", "masc du", "masc pl", "fem sg", "fem du", "fem pl", "neut sg",
                    "neut du", "neut pl",
                ],
            );
        }
        Conjugation::Cat(t) => {
            s.one(&t.infinitive, "infinitive");
            s.one(&t.gerund, "gerund");
            s.one(&t.past_participle, "past participle");
            s.row_opt(
                &t.imperative,
                "imperative",
                &["tu", "vostè", "nosaltres", "vosaltres", "vostès"],
            );
            s.row(&t.present, "present", &P6);
            s.row(&t.imperfect, "imperfect", &P6);
            s.row(&t.preterite, "preterite", &P6);
            s.row(&t.future, "future", &P6);
            s.row(&t.conditional, "conditional", &P6);
            s.row(&t.subjunctive_present, "subjunctive present", &P6);
            s.row(&t.subjunctive_imperfect, "subjunctive imperfect", &P6);
        }
        Conjugation::Ukr(t) => {
            s.one(&t.infinitive, "infinitive");
            s.row(&t.present, "present", &P6);
            s.row_opt(&t.imperative, "imperative", &["2sg", "1pl", "2pl"]);
            s.row(&t.past, "past", &["masc sg", "fem sg", "neut sg", "pl"]);
        }
        Conjugation::Spa(t) => {
            s.one(&t.infinitive, "infinitive");
            s.one(&t.gerund, "gerund");
            s.one(&t.past_participle, "past participle");
            s.opt(t.present_vos.as_ref(), "present 2sg (vos)");
            s.opt(t.imperative_vos.as_ref(), "imperative vos");
            s.row_opt(
                &t.imperative,
                "imperative",
                &["tú", "usted", "nosotros", "vosotros", "ustedes"],
            );
            s.row(&t.present, "present", &P6);
            s.row(&t.imperfect, "imperfect", &P6);
            s.row(&t.preterite, "preterite", &P6);
            s.row(&t.future, "future", &P6);
            s.row(&t.conditional, "conditional", &P6);
            s.row(&t.subjunctive_present, "subjunctive present", &P6);
            s.row(&t.subjunctive_imperfect, "subjunctive imperfect", &P6);
            s.row(&t.subjunctive_future, "subjunctive future", &P6);
        }
        Conjugation::Swe(t) => {
            s.one(&t.infinitive, "infinitive");
            s.opt(t.present.as_ref(), "present");
            s.opt(t.past.as_ref(), "past");
            s.opt(t.supine.as_ref(), "supine");
            s.opt(t.imperative.as_ref(), "imperative");
            s.opt(t.infinitive_passive.as_ref(), "passive infinitive");
            s.opt(t.present_passive.as_ref(), "passive present");
            s.opt(t.past_passive.as_ref(), "passive past");
            s.opt(t.supine_passive.as_ref(), "passive supine");
            s.opt(t.subjunctive_past.as_ref(), "past subjunctive");
        }
        Conjugation::Isl(t) => {
            s.one(&t.infinitive, "infinitive");
            s.one(&t.supine, "supine");
            s.one(&t.present_participle, "present participle");
            s.row_opt(&t.imperative, "imperative", &["þú", "þið"]);
            s.row(&t.present, "present", &P6);
            s.row(&t.past, "past", &P6);
            s.row(&t.subjunctive_present, "subjunctive present", &P6);
            s.row(&t.subjunctive_past, "subjunctive past", &P6);
        }
    }
    s.0
}

#[cfg(test)]
mod tests {
    use super::*;

    fn infs(form: &str, lang: Lang) -> Vec<String> {
        reverse(form, lang)
            .into_iter()
            .map(|m| m.infinitive)
            .collect()
    }

    #[test]
    fn french_suis_is_etre_and_suivre() {
        let m = reverse("suis", Lang::Fra);
        assert_eq!(infs("suis", Lang::Fra), ["suivre", "être"]); // byte order
        let etre = m.iter().find(|m| m.infinitive == "être").unwrap();
        let suivre = m.iter().find(|m| m.infinitive == "suivre").unwrap();
        assert!(etre.slots.contains(&"present 1sg".to_string()));
        assert!(suivre.slots.contains(&"present 1sg".to_string()));
        assert!(suivre.slots.contains(&"present 2sg".to_string()));
    }

    #[test]
    fn french_productive_and_twins() {
        assert!(infs("appellerons", Lang::Fra).contains(&"appeler".to_string()));
        assert!(infs("finissons", Lang::Fra).contains(&"finir".to_string()));
        assert!(infs("cèderai", Lang::Fra).contains(&"céder".to_string()));
        assert!(infs("paie", Lang::Fra).contains(&"payer".to_string()));
    }

    #[test]
    fn german_trinkst_and_war() {
        assert!(infs("trinkst", Lang::Deu).contains(&"trinken".to_string()));
        assert_eq!(infs("war", Lang::Deu), ["sein"]);
        assert!(infs("gekauft", Lang::Deu).contains(&"kaufen".to_string()));
        assert!(infs("anzufangen", Lang::Deu).contains(&"anfangen".to_string()));
    }

    #[test]
    fn english_went_and_regulars() {
        assert_eq!(infs("went", Lang::Eng), ["go"]);
        assert!(infs("walks", Lang::Eng).contains(&"walk".to_string()));
        assert!(infs("stopped", Lang::Eng).contains(&"stop".to_string()));
        assert!(infs("tries", Lang::Eng).contains(&"try".to_string()));
    }

    #[test]
    fn spanish_hable_and_fue() {
        assert_eq!(infs("hablé", Lang::Spa), ["hablar"]);
        let fue = infs("fue", Lang::Spa);
        assert!(fue.contains(&"ser".to_string()) && fue.contains(&"ir".to_string()));
        assert!(infs("cuento", Lang::Spa).contains(&"contar".to_string()));
    }

    #[test]
    fn index_only_languages() {
        assert!(infs("chuaigh", Lang::Gle).contains(&"téigh".to_string()));
        assert!(infs("mindes", Lang::Swe).contains(&"minnas".to_string()));
        assert!(infs("fui", Lang::Por).contains(&"ser".to_string()));
    }

    #[test]
    fn input_is_folded_like_from_infinitive() {
        assert_eq!(infs("  Suis \n", Lang::Fra), ["suivre", "être"]);
        assert!(infs("", Lang::Fra).is_empty());
        assert!(infs("kauft an", Lang::Deu).is_empty());
    }
}
