//! Albanian conjugation. Albanian is cited (no infinitive) by its 1sg
//! present indicative. The productive -oj class (abdikoj — the large,
//! regular class of denominatives and loanwords) is generated by rule:
//! present, imperfect and aorist indicative, admirative present and
//! imperfect, imperative and participle. Every other class (consonant
//! stems, -ë verbs, suppletives) and every irregular -oj verb carries a
//! mined row in `data/sqi/parts.tsv`, matched exactly. The subjunctive,
//! optative, perfect and future are analytic (të / do / ka + form) and
//! out of scope.

use std::collections::HashMap;
use std::sync::OnceLock;

/// The stored cells, in the column order of `data/sqi/parts.tsv`.
pub const CELLS: [&str; 33] = [
    "V;1;SG;IND;PRS",
    "V;2;SG;IND;PRS",
    "V;3;SG;IND;PRS",
    "V;1;PL;IND;PRS",
    "V;2;PL;IND;PRS",
    "V;3;PL;IND;PRS",
    "V;1;SG;IND;IPFV",
    "V;2;SG;IND;IPFV",
    "V;3;SG;IND;IPFV",
    "V;1;PL;IND;IPFV",
    "V;2;PL;IND;IPFV",
    "V;3;PL;IND;IPFV",
    "V;1;SG;IND;PST",
    "V;2;SG;IND;PST",
    "V;3;SG;IND;PST",
    "V;1;PL;IND;PST",
    "V;2;PL;IND;PST",
    "V;3;PL;IND;PST",
    "V;1;SG;ADM;PRS",
    "V;2;SG;ADM;PRS",
    "V;3;SG;ADM;PRS",
    "V;1;PL;ADM;PRS",
    "V;2;PL;ADM;PRS",
    "V;3;PL;ADM;PRS",
    "V;1;SG;ADM;IPFV",
    "V;2;SG;ADM;IPFV",
    "V;3;SG;ADM;IPFV",
    "V;1;PL;ADM;IPFV",
    "V;2;PL;ADM;IPFV",
    "V;3;PL;ADM;IPFV",
    "V;2;SG;IMP",
    "V;2;PL;IMP",
    "V;V.PTCP",
];

/// Why a form cannot be produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The input does not look like an Albanian 1sg-present citation.
    NotAVerb,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "not an Albanian verb")
    }
}

static PARTS_TSV: &str = include_str!("../data/sqi/parts.tsv");

fn overrides(cit: &str) -> Option<HashMap<&'static str, &'static str>> {
    static MAP: OnceLock<HashMap<&'static str, HashMap<&'static str, &'static str>>> =
        OnceLock::new();
    let map = MAP.get_or_init(|| {
        let mut m = HashMap::new();
        for line in PARTS_TSV.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let mut cols = line.split('\t');
            let Some(lemma) = cols.next() else { continue };
            let mut row = HashMap::new();
            for (i, val) in cols.enumerate() {
                if val != "-" && !val.is_empty() {
                    if let Some(feat) = CELLS.get(i) {
                        row.insert(*feat, val);
                    }
                }
            }
            m.insert(lemma, row);
        }
        m
    });
    map.get(cit).cloned()
}

/// The -oj-class ending for a feature bundle body ("P;N;MOOD;TENSE"),
/// or None if the paradigm is not one of the productive ones.
fn oj_ending(body: &str) -> Option<&'static str> {
    // (para, [1sg,2sg,3sg,1pl,2pl,3pl])
    let (pn, para) = {
        let mut it = body.splitn(3, ';');
        let p = it.next()?;
        let n = it.next()?;
        let para = it.next()?;
        (format!("{p};{n}"), para.to_string())
    };
    let table: [(&str, [&str; 6]); 5] = [
        ("IND;PRS", ["oj", "on", "on", "ojmë", "oni", "ojnë"]),
        ("IND;IPFV", ["oja", "oje", "onte", "onim", "onit", "onin"]),
        ("IND;PST", ["ova", "ove", "oi", "uam", "uat", "uan"]),
        (
            "ADM;PRS",
            ["uakam", "uake", "uaka", "uakemi", "uakeni", "uakan"],
        ),
        (
            "ADM;IPFV",
            [
                "uakësha",
                "uakëshe",
                "uakësh",
                "uakëshim",
                "uakëshit",
                "uakëshin",
            ],
        ),
    ];
    let idx = match pn.as_str() {
        "1;SG" => 0,
        "2;SG" => 1,
        "3;SG" => 2,
        "1;PL" => 3,
        "2;PL" => 4,
        "3;PL" => 5,
        _ => return None,
    };
    table
        .iter()
        .find(|(p, _)| *p == para)
        .map(|(_, ends)| ends[idx])
}

/// The productive -oj-class form, or None if the citation is not -oj.
fn productive(cit: &str, feat: &str) -> Option<String> {
    let stem = cit.strip_suffix("oj")?;
    match feat {
        "V;V.PTCP" => Some(format!("{stem}uar")),
        "V;2;SG;IMP" => Some(format!("{stem}o")),
        "V;2;PL;IMP" => Some(format!("{stem}oni")),
        _ => {
            let body = feat.strip_prefix("V;")?;
            oj_ending(body).map(|e| format!("{stem}{e}"))
        }
    }
}

/// A conjugatable Albanian verb, cited by its 1sg present indicative.
#[derive(Debug, Clone)]
pub struct Verb {
    citation: String,
    overrides: HashMap<&'static str, &'static str>,
}

impl Verb {
    /// Build a verb from its 1sg present-indicative citation form.
    pub fn from_infinitive(citation: &str) -> Result<Self, Error> {
        let lowered = citation.trim().to_lowercase();
        let cit = if overrides(citation.trim()).is_none() && overrides(&lowered).is_some() {
            lowered.clone()
        } else {
            citation.trim().to_string()
        };
        if cit.is_empty() || cit.contains(char::is_whitespace) {
            return Err(Error::NotAVerb);
        }
        let over = overrides(&cit).unwrap_or_default();
        if over.is_empty() && !cit.ends_with("oj") {
            return Err(Error::NotAVerb);
        }
        Ok(Self {
            citation: cit,
            overrides: over,
        })
    }

    /// The citation form (1sg present indicative).
    pub fn citation(&self) -> &str {
        &self.citation
    }

    /// The form for a UniMorph feature bundle: a mined override if one
    /// exists, else the productive -oj-class rule.
    pub fn form(&self, feature: &str) -> Option<String> {
        if let Some(f) = self.overrides.get(feature) {
            return Some((*f).to_string());
        }
        productive(&self.citation, feature)
    }
}

/// A compact conjugation table — the synthetic paradigm, shared by the
/// WebAssembly and Python bindings.
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct Table {
    /// 1sg present indicative (the citation).
    pub present: String,
    /// Present indicative, 1sg/2sg/3sg/1pl/2pl/3pl.
    pub present_all: Vec<Option<String>>,
    /// Imperfect indicative, same order.
    pub imperfect: Vec<Option<String>>,
    /// Aorist indicative, same order.
    pub aorist: Vec<Option<String>>,
    /// Admirative present, same order.
    pub admirative: Vec<Option<String>>,
    /// Imperative 2sg/2pl.
    pub imperative: Vec<Option<String>>,
    pub participle: Option<String>,
}

impl Table {
    #[must_use]
    pub fn build(v: &Verb) -> Self {
        let many = |feats: &[&str]| feats.iter().map(|f| v.form(f)).collect();
        Self {
            present: v.citation().to_string(),
            present_all: many(&[
                "V;1;SG;IND;PRS",
                "V;2;SG;IND;PRS",
                "V;3;SG;IND;PRS",
                "V;1;PL;IND;PRS",
                "V;2;PL;IND;PRS",
                "V;3;PL;IND;PRS",
            ]),
            imperfect: many(&[
                "V;1;SG;IND;IPFV",
                "V;2;SG;IND;IPFV",
                "V;3;SG;IND;IPFV",
                "V;1;PL;IND;IPFV",
                "V;2;PL;IND;IPFV",
                "V;3;PL;IND;IPFV",
            ]),
            aorist: many(&[
                "V;1;SG;IND;PST",
                "V;2;SG;IND;PST",
                "V;3;SG;IND;PST",
                "V;1;PL;IND;PST",
                "V;2;PL;IND;PST",
                "V;3;PL;IND;PST",
            ]),
            admirative: many(&[
                "V;1;SG;ADM;PRS",
                "V;2;SG;ADM;PRS",
                "V;3;SG;ADM;PRS",
                "V;1;PL;ADM;PRS",
                "V;2;PL;ADM;PRS",
                "V;3;PL;ADM;PRS",
            ]),
            imperative: many(&["V;2;SG;IMP", "V;2;PL;IMP"]),
            participle: v.form("V;V.PTCP"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(cit: &str) -> Verb {
        Verb::from_infinitive(cit).unwrap()
    }

    #[test]
    fn oj_class_productive() {
        let a = v("abdikoj");
        assert_eq!(a.form("V;3;SG;IND;PRS").unwrap(), "abdikon");
        assert_eq!(a.form("V;1;PL;IND;PRS").unwrap(), "abdikojmë");
        assert_eq!(a.form("V;3;SG;IND;IPFV").unwrap(), "abdikonte");
        assert_eq!(a.form("V;1;SG;IND;PST").unwrap(), "abdikova");
        assert_eq!(a.form("V;1;PL;IND;PST").unwrap(), "abdikuam");
        assert_eq!(a.form("V;3;SG;ADM;PRS").unwrap(), "abdikuaka");
        assert_eq!(a.form("V;2;SG;IMP").unwrap(), "abdiko");
        assert_eq!(a.form("V;V.PTCP").unwrap(), "abdikuar");
    }
}
