//! Turkmen conjugation. Turkmen is an Oghuz Turkic language cited by its
//! infinitive (-mak / -mek). The synthetic core — present (-ýar), past
//! definite (-dy), aorist (-ar), the two imperatives and the infinitive —
//! is generated by two-way vowel harmony (low A ∈ {a, ä}, high I ∈ {y, i})
//! from the stem; irregular and e/ä-front verbs carry a mined row in
//! `data/tuk/parts.tsv`. Turkmen's phonemic vowel length (marked with a
//! macron in the source, omitted in standard orthography) is normalised
//! away. Verified against one oracle (kaikki.org): Beta.

use std::collections::HashMap;
use std::sync::OnceLock;

/// The stored cells, in the column order of `data/tuk/parts.tsv`.
pub const CELLS: [&str; 21] = [
    "V;PRS;1;SG", "V;PRS;2;SG", "V;PRS;3;SG", "V;PRS;1;PL", "V;PRS;2;PL", "V;PRS;3;PL",
    "V;PST;1;SG", "V;PST;2;SG", "V;PST;3;SG", "V;PST;1;PL", "V;PST;2;PL", "V;PST;3;PL",
    "V;AOR;1;SG", "V;AOR;2;SG", "V;AOR;3;SG", "V;AOR;1;PL", "V;AOR;2;PL", "V;AOR;3;PL",
    "V;IMP;2;SG", "V;IMP;2;PL", "V;NFIN",
];

/// Why a form cannot be produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The input does not look like a Turkmen infinitive.
    NotAVerb,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "not a Turkmen infinitive")
    }
}

static PARTS_TSV: &str = include_str!("../data/tuk/parts.tsv");

fn overrides(cit: &str) -> Option<HashMap<&'static str, &'static str>> {
    static MAP: OnceLock<HashMap<&'static str, HashMap<&'static str, &'static str>>> =
        OnceLock::new();
    let map = MAP.get_or_init(|| {
        let mut m = HashMap::new();
        for line in PARTS_TSV.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let mut cols = line.split('\t');
            let Some(lemma) = cols.next() else { continue };
            let mut row = HashMap::new();
            for (i, val) in cols.enumerate() {
                if val != "-" && !val.is_empty() {
                    if let Some(feat) = CELLS.get(i) {
                        row.insert(*feat, val);
                    }
                }
            }
            m.insert(lemma, row);
        }
        m
    });
    map.get(cit).cloned()
}

const BACK: &str = "ayou";
const VOWELS: &str = "ayouäeiöü";

/// The productive harmony-generated form, or None for a non-verb citation.
fn productive(cit: &str, feat: &str) -> Option<String> {
    if !(cit.ends_with("mak") || cit.ends_with("mek")) {
        return None;
    }
    if feat == "V;NFIN" {
        return Some(cit.to_string());
    }
    let n = cit.chars().count();
    let stem: String = cit.chars().take(n - 3).collect();
    let v = stem.chars().rev().find(|c| VOWELS.contains(*c)).unwrap_or('ä');
    let back = BACK.contains(v);
    let a = if back { 'a' } else { 'ä' };
    let i = if back { 'y' } else { 'i' };
    let ler = if back { "lar" } else { "ler" };

    let cop = |pn: &str| -> String {
        match pn {
            "1;SG" => format!("{i}n"),
            "2;SG" => format!("s{i}n"),
            "3;SG" => String::new(),
            "1;PL" => format!("{i}s"),
            "2;PL" => format!("s{i}ň{i}z"),
            "3;PL" => ler.to_string(),
            _ => String::new(),
        }
    };
    let past = |pn: &str| -> String {
        match pn {
            "1;SG" => "m".into(),
            "2;SG" => "ň".into(),
            "3;SG" => String::new(),
            "1;PL" => "k".into(),
            "2;PL" => format!("ň{i}z"),
            "3;PL" => ler.to_string(),
            _ => String::new(),
        }
    };

    if feat == "V;IMP;2;SG" {
        return Some(stem);
    }
    if feat == "V;IMP;2;PL" {
        return Some(format!("{stem}{i}ň"));
    }
    let parts: Vec<&str> = feat.split(';').collect();
    let pn = format!("{};{}", parts[2], parts[3]);
    Some(match parts[1] {
        "PRS" => format!("{stem}ý{a}r{}", cop(&pn)),
        "PST" => format!("{stem}d{i}{}", past(&pn)),
        "AOR" => format!("{stem}{a}r{}", cop(&pn)),
        _ => return None,
    })
}

/// A conjugatable Turkmen verb, cited by its infinitive.
#[derive(Debug, Clone)]
pub struct Verb {
    citation: String,
    overrides: HashMap<&'static str, &'static str>,
}

impl Verb {
    /// Build a verb from its infinitive (-mak / -mek).
    pub fn from_infinitive(citation: &str) -> Result<Self, Error> {
        let lowered = citation.trim().to_lowercase();
        let cit = if overrides(citation.trim()).is_none() && overrides(&lowered).is_some() {
            lowered.clone()
        } else {
            citation.trim().to_string()
        };
        if cit.is_empty() || cit.contains(char::is_whitespace) {
            return Err(Error::NotAVerb);
        }
        if !cit.ends_with("mak") && !cit.ends_with("mek") && overrides(&cit).is_none() {
            return Err(Error::NotAVerb);
        }
        let over = overrides(&cit).unwrap_or_default();
        Ok(Self {
            citation: cit,
            overrides: over,
        })
    }

    /// The infinitive (citation).
    pub fn citation(&self) -> &str {
        &self.citation
    }

    /// The form for a feature bundle: a mined override if one exists, else
    /// the productive harmony rule.
    pub fn form(&self, feature: &str) -> Option<String> {
        if let Some(f) = self.overrides.get(feature) {
            return Some((*f).to_string());
        }
        productive(&self.citation, feature)
    }
}

/// A compact conjugation table — the synthetic core, shared by the
/// WebAssembly and Python bindings.
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct Table {
    /// Infinitive (the citation).
    pub infinitive: String,
    /// Present, 1sg/2sg/3sg/1pl/2pl/3pl.
    pub present: Vec<Option<String>>,
    /// Past definite, same order.
    pub past: Vec<Option<String>>,
    /// Aorist, same order.
    pub aorist: Vec<Option<String>>,
    /// Imperative 2sg/2pl.
    pub imperative: Vec<Option<String>>,
}

impl Table {
    #[must_use]
    pub fn build(v: &Verb) -> Self {
        let many = |feats: &[&str]| feats.iter().map(|f| v.form(f)).collect();
        Self {
            infinitive: v.citation().to_string(),
            present: many(&[
                "V;PRS;1;SG", "V;PRS;2;SG", "V;PRS;3;SG", "V;PRS;1;PL", "V;PRS;2;PL", "V;PRS;3;PL",
            ]),
            past: many(&[
                "V;PST;1;SG", "V;PST;2;SG", "V;PST;3;SG", "V;PST;1;PL", "V;PST;2;PL", "V;PST;3;PL",
            ]),
            aorist: many(&[
                "V;AOR;1;SG", "V;AOR;2;SG", "V;AOR;3;SG", "V;AOR;1;PL", "V;AOR;2;PL", "V;AOR;3;PL",
            ]),
            imperative: many(&["V;IMP;2;SG", "V;IMP;2;PL"]),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(cit: &str) -> Verb {
        Verb::from_infinitive(cit).unwrap()
    }

    #[test]
    fn back_harmony() {
        let a = v("atmak"); // stem at-, back
        assert_eq!(a.form("V;PRS;1;SG").unwrap(), "atýaryn");
        assert_eq!(a.form("V;PRS;3;SG").unwrap(), "atýar");
        assert_eq!(a.form("V;PST;1;SG").unwrap(), "atdym");
        assert_eq!(a.form("V;AOR;3;SG").unwrap(), "atar");
        assert_eq!(a.form("V;NFIN").unwrap(), "atmak");
    }
}
