//! Ukrainian conjugation. East Slavic, two conjugations. The non-past
//! finite paradigm is the imperfective present (читаю) and the
//! perfective non-past, which carries future meaning (прочитаю) —
//! morphologically one slot set. The l-past marks gender in the
//! singular (читав/читала/читало) and only number in the plural
//! (читали). The imperative has 2sg/1pl/2pl.
//!
//! The productive first conjugation with a vowel stem (читати →
//! читаю, купувати → купую) and the second conjugation with its
//! 1sg/3pl consonant mutations (робити → роблю/роблять, сидіти →
//! сиджу/сидять) are generated by rule; every stem-changing or
//! athematic verb is an explicit row in `data/ukr/verbs.tsv`, mined
//! from the agreement of the two oracles. Reflexive (-ся) verbs
//! compose the base paradigm with the postfix, unless stored.

use std::collections::HashMap;
use std::sync::OnceLock;

/// Grammatical person.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Person {
    First,
    Second,
    Third,
}

/// Grammatical number.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Number {
    Singular,
    Plural,
}

/// The three genders the l-past distinguishes in the singular.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Gender {
    Masculine,
    Feminine,
    Neuter,
}

/// Why an infinitive cannot be conjugated.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The input does not look like a Ukrainian infinitive.
    NotAVerb,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "not a Ukrainian infinitive")
    }
}

/// Present (non-past) conjugation class.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Class {
    /// First conjugation, vowel stem: -ати/-яти/-увати/-ювати
    /// (читаю, купую) — the e/є-endings on a vowel-final stem.
    Aje,
    /// Second conjugation: -ити/-іти/-їти (роблю, сиджу, говорю) —
    /// the и-endings with 1sg/3pl consonant mutation.
    It,
}

static VERBS_TSV: &str = include_str!("../data/ukr/verbs.tsv");

/// Explicit row: present 1sg…3pl, imperative 2sg/1pl/2pl, past
/// masc/fem/neut/pl ("-" = derive).
#[derive(Debug, Clone, Default)]
struct Row {
    present: [Option<String>; 6],
    imp: [Option<String>; 3],
    past: [Option<String>; 4],
}

fn rows() -> &'static HashMap<&'static str, Row> {
    static MAP: OnceLock<HashMap<&'static str, Row>> = OnceLock::new();
    MAP.get_or_init(|| {
        let mut m = HashMap::new();
        for line in VERBS_TSV.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let cols: Vec<&str> = line.split('\t').collect();
            let opt = |i: usize| {
                cols.get(i)
                    .filter(|c| **c != "-" && !c.is_empty())
                    .map(|c| (*c).to_string())
            };
            m.insert(
                cols[0],
                Row {
                    present: [opt(1), opt(2), opt(3), opt(4), opt(5), opt(6)],
                    imp: [opt(7), opt(8), opt(9)],
                    past: [opt(10), opt(11), opt(12), opt(13)],
                },
            );
        }
        m
    })
}

/// A conjugatable Ukrainian verb.
#[derive(Debug, Clone)]
pub struct Verb {
    infinitive: String,
    /// The non-reflexive base infinitive (митися → мити), used for
    /// rule-based composition of reflexive forms.
    base: String,
    reflexive: bool,
    stem: String,
    class: Class,
    row: Row,
}

const SIBILANTS: [&str; 5] = ["дж", "ж", "ч", "ш", "щ"];
const LABIALS: [char; 5] = ['б', 'п', 'в', 'м', 'ф'];

impl Verb {
    /// Build a verb from its infinitive.
    pub fn from_infinitive(infinitive: &str) -> Result<Self, Error> {
        // The apostrophe (marking a hard consonant before я/ю/є/ї, as in
        // в'язати) is a letter here; normalize the curly form to ASCII so
        // either spelling reaches the same lexicon key.
        let lowered = infinitive.to_lowercase().replace('\u{2019}', "'");
        let inf = lowered.trim();
        if inf.is_empty()
            || inf.contains(char::is_whitespace)
            || !inf
                .chars()
                .all(|c| c.is_alphabetic() || c == '-' || c == '\'')
        {
            return Err(Error::NotAVerb);
        }
        // A reflexive infinitive ends in the postfix -ся/-сь.
        let (base, reflexive) =
            if let Some(b) = inf.strip_suffix("ся").or_else(|| inf.strip_suffix("сь")) {
                (b.to_string(), true)
            } else {
                (inf.to_string(), false)
            };
        let (stem, class) = classify(&base);
        Ok(Self {
            infinitive: inf.to_string(),
            base,
            reflexive,
            stem,
            class,
            row: rows().get(inf).cloned().unwrap_or_default(),
        })
    }

    /// The infinitive as normalized.
    #[must_use]
    pub fn infinitive(&self) -> &str {
        &self.infinitive
    }

    fn idx(person: Person, number: Number) -> usize {
        let p = match person {
            Person::First => 0,
            Person::Second => 1,
            Person::Third => 2,
        };
        p + if number == Number::Plural { 3 } else { 0 }
    }

    /// Attach the reflexive postfix -ся to a composed form.
    fn reflex(&self, form: String) -> String {
        if self.reflexive {
            format!("{form}ся")
        } else {
            form
        }
    }

    /// The non-past finite form (present for imperfectives, future for
    /// perfectives).
    #[must_use]
    pub fn present(&self, person: Person, number: Number) -> String {
        if let Some(f) = &self.row.present[Self::idx(person, number)] {
            return f.clone();
        }
        self.reflex(self.rule_present(Self::idx(person, number)))
    }

    /// The rule-generated non-past of the base (non-reflexive) verb.
    fn rule_present(&self, i: usize) -> String {
        let s = &self.stem;
        match self.class {
            Class::Aje => {
                let e = ["ю", "єш", "є", "ємо", "єте", "ють"];
                format!("{s}{}", e[i])
            }
            Class::It => {
                let last = s.chars().last().unwrap_or(' ');
                let labial = LABIALS.contains(&last);
                match i {
                    0 => {
                        // 1sg mutates the stem-final consonant.
                        let m = mutate(s);
                        let v = if m.ends_with('л') || !ends_sibilant(&m) {
                            "ю"
                        } else {
                            "у"
                        };
                        format!("{m}{v}")
                    }
                    1 => format!("{s}иш"),
                    2 => format!("{s}ить"),
                    3 => format!("{s}имо"),
                    4 => format!("{s}ите"),
                    5 => {
                        if labial {
                            format!("{s}лять")
                        } else if ends_sibilant(s) {
                            format!("{s}ать")
                        } else {
                            format!("{s}ять")
                        }
                    }
                    _ => unreachable!(),
                }
            }
        }
    }

    /// An imperative form (2sg, 1pl, 2pl).
    #[must_use]
    pub fn imperative(&self, person: Person, number: Number) -> Option<String> {
        let slot = match (number, person) {
            (Number::Singular, Person::Second) => 0,
            (Number::Plural, Person::First) => 1,
            (Number::Plural, Person::Second) => 2,
            _ => return None,
        };
        if let Some(f) = &self.row.imp[slot] {
            return Some(f.clone());
        }
        let s = &self.stem;
        let base = match self.class {
            Class::Aje => match slot {
                0 => format!("{s}й"),
                1 => format!("{s}ймо"),
                _ => format!("{s}йте"),
            },
            Class::It => match slot {
                0 => format!("{s}и"),
                1 => format!("{s}імо"),
                _ => format!("{s}іть"),
            },
        };
        Some(self.reflex(base))
    }

    /// The l-past. The masculine singular is base + -в, the feminine
    /// -ла, the neuter -ло, the plural -ли (читав/читала/читало/читали).
    #[must_use]
    pub fn past(&self, gender: Gender, number: Number) -> String {
        let slot = match (number, gender) {
            (Number::Singular, Gender::Masculine) => 0,
            (Number::Singular, Gender::Feminine) => 1,
            (Number::Singular, Gender::Neuter) => 2,
            (Number::Plural, _) => 3,
        };
        if let Some(f) = &self.row.past[slot] {
            return f.clone();
        }
        let b = self.base.strip_suffix("ти").unwrap_or(&self.base);
        let suffix = ["в", "ла", "ло", "ли"][slot];
        self.reflex(format!("{b}{suffix}"))
    }
}

/// True if the string ends in a hard sibilant (ж/ч/ш/щ or дж), which
/// takes the hard 1sg -у and 3pl -ать.
fn ends_sibilant(s: &str) -> bool {
    SIBILANTS.iter().any(|z| s.ends_with(z))
}

/// The 1sg/labial-3pl consonant mutation of a second-conjugation stem:
/// д→дж, т→ч, з→ж, с→ш, ст→щ, зд→ждж; a labial inserts -л-
/// (роб→робл, лов→ловл). Other finals pass through (говор→говор).
fn mutate(stem: &str) -> String {
    for (from, to) in [("ст", "щ"), ("зд", "ждж")] {
        if let Some(b) = stem.strip_suffix(from) {
            return format!("{b}{to}");
        }
    }
    let mut chars: Vec<char> = stem.chars().collect();
    let Some(&last) = chars.last() else {
        return stem.to_string();
    };
    if LABIALS.contains(&last) {
        return format!("{stem}л");
    }
    let repl = match last {
        'д' => "дж",
        'т' => "ч",
        'з' => "ж",
        'с' => "ш",
        _ => return stem.to_string(),
    };
    chars.pop();
    format!("{}{repl}", chars.into_iter().collect::<String>())
}

/// Split an infinitive into its present stem and conjugation class.
fn classify(inf: &str) -> (String, Class) {
    for suf in ["увати", "ювати"] {
        if let Some(b) = inf.strip_suffix(suf) {
            // -ува-/-юва- contracts to -у-/-ю- in the present.
            let v = if suf == "ювати" { "ю" } else { "у" };
            return (format!("{b}{v}"), Class::Aje);
        }
    }
    for suf in ["ити", "їти", "іти"] {
        if let Some(b) = inf.strip_suffix(suf) {
            return (b.to_string(), Class::It);
        }
    }
    for suf in ["ати", "яти"] {
        if let Some(b) = inf.strip_suffix("ти") {
            let _ = suf;
            return (b.to_string(), Class::Aje);
        }
    }
    // Fallback: strip -ти, treat as vowel-stem first conjugation. Verbs
    // this misfits are carried by explicit rows.
    (
        inf.strip_suffix("ти").unwrap_or(inf).to_string(),
        Class::Aje,
    )
}

/// The full conjugation table of a Ukrainian verb — shared by the
/// WebAssembly and Python bindings.
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct Table {
    pub infinitive: String,
    /// The non-past finite paradigm, [1sg…3pl].
    pub present: [String; 6],
    /// [2sg, 1pl, 2pl].
    pub imperative: [Option<String>; 3],
    /// The l-past: [masc sg, fem sg, neut sg, plural].
    pub past: [String; 4],
}

impl Table {
    #[must_use]
    pub fn build(v: &Verb) -> Self {
        Self {
            infinitive: v.infinitive().to_string(),
            present: [
                v.present(Person::First, Number::Singular),
                v.present(Person::Second, Number::Singular),
                v.present(Person::Third, Number::Singular),
                v.present(Person::First, Number::Plural),
                v.present(Person::Second, Number::Plural),
                v.present(Person::Third, Number::Plural),
            ],
            imperative: [
                v.imperative(Person::Second, Number::Singular),
                v.imperative(Person::First, Number::Plural),
                v.imperative(Person::Second, Number::Plural),
            ],
            past: [
                v.past(Gender::Masculine, Number::Singular),
                v.past(Gender::Feminine, Number::Singular),
                v.past(Gender::Neuter, Number::Singular),
                v.past(Gender::Masculine, Number::Plural),
            ],
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(inf: &str) -> Verb {
        Verb::from_infinitive(inf).unwrap()
    }

    #[test]
    fn first_conjugation_vowel_stem() {
        let c = v("читати");
        assert_eq!(c.present(Person::First, Number::Singular), "читаю");
        assert_eq!(c.present(Person::Second, Number::Singular), "читаєш");
        assert_eq!(c.present(Person::Third, Number::Plural), "читають");
        assert_eq!(
            c.imperative(Person::Second, Number::Singular).unwrap(),
            "читай"
        );
        assert_eq!(c.past(Gender::Masculine, Number::Singular), "читав");
        assert_eq!(c.past(Gender::Feminine, Number::Singular), "читала");
        let k = v("купувати");
        assert_eq!(k.present(Person::First, Number::Singular), "купую");
        assert_eq!(k.present(Person::Second, Number::Plural), "купуєте");
    }

    #[test]
    fn second_conjugation_mutations() {
        let r = v("робити");
        assert_eq!(r.present(Person::First, Number::Singular), "роблю");
        assert_eq!(r.present(Person::Second, Number::Singular), "робиш");
        assert_eq!(r.present(Person::Third, Number::Plural), "роблять");
        let s = v("сидіти");
        assert_eq!(s.present(Person::First, Number::Singular), "сиджу");
        assert_eq!(s.present(Person::Third, Number::Plural), "сидять");
        let n = v("носити");
        assert_eq!(n.present(Person::First, Number::Singular), "ношу");
        assert_eq!(n.present(Person::Third, Number::Plural), "носять");
        let g = v("говорити");
        assert_eq!(g.present(Person::First, Number::Singular), "говорю");
        assert_eq!(g.present(Person::Third, Number::Plural), "говорять");
    }

    /// The rule path composes a reflexive from the base paradigm plus
    /// the -ся postfix. Exercised on a nonce -атися verb so no mined
    /// lexicon row (which the common reflexives all carry) intercepts it.
    #[test]
    fn reflexive_composition() {
        let u = v("абабатися");
        assert!(rows().get("абабатися").is_none());
        assert_eq!(u.present(Person::First, Number::Singular), "абабаюся");
        assert_eq!(u.present(Person::Second, Number::Singular), "абабаєшся");
        assert_eq!(u.past(Gender::Masculine, Number::Singular), "абабався");
        assert_eq!(u.past(Gender::Feminine, Number::Singular), "абабалася");
        assert_eq!(
            u.imperative(Person::Second, Number::Singular).unwrap(),
            "абабайся"
        );
    }
}
