//! Uzbek conjugation. Uzbek is an agglutinative Turkic language that has
//! largely lost vowel harmony, so its suffixes are invariant. It is cited
//! by its infinitive (-moq). The third-person present (-adi / -ydi), past
//! definite (-di), future definite (-ajak), aorist (-ar) and imperative
//! (-sin) core is generated by rule; irregular stems carry a mined row in
//! `data/uzb/parts.tsv`. Verified against one oracle (kaikki.org): Beta,
//! and third-person only, matching the extent of the oracle's tables. The
//! remaining persons and the continuative/perfective aspects are a later
//! pass.

use std::collections::HashMap;
use std::sync::OnceLock;

/// The stored cells, in the column order of `data/uzb/parts.tsv`.
pub const CELLS: [&str; 11] = [
    "V;PRS;3;SG", "V;PRS;3;PL", "V;PST;3;SG", "V;PST;3;PL", "V;FUT;3;SG", "V;FUT;3;PL",
    "V;AOR;3;SG", "V;AOR;3;PL", "V;IMP;3;SG", "V;IMP;3;PL", "V;NFIN",
];

/// Why a form cannot be produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The input does not look like an Uzbek infinitive.
    NotAVerb,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "not an Uzbek infinitive")
    }
}

static PARTS_TSV: &str = include_str!("../data/uzb/parts.tsv");

fn overrides(cit: &str) -> Option<HashMap<&'static str, &'static str>> {
    static MAP: OnceLock<HashMap<&'static str, HashMap<&'static str, &'static str>>> =
        OnceLock::new();
    let map = MAP.get_or_init(|| {
        let mut m = HashMap::new();
        for line in PARTS_TSV.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let mut cols = line.split('\t');
            let Some(lemma) = cols.next() else { continue };
            let mut row = HashMap::new();
            for (i, val) in cols.enumerate() {
                if val != "-" && !val.is_empty() {
                    if let Some(feat) = CELLS.get(i) {
                        row.insert(*feat, val);
                    }
                }
            }
            m.insert(lemma, row);
        }
        m
    });
    map.get(cit).cloned()
}

const VOWELS: &str = "aeiouoʻ";

/// The productive suffix-generated form, or None for a non-verb citation.
fn productive(cit: &str, feat: &str) -> Option<String> {
    let stem = cit.strip_suffix("moq")?;
    if feat == "V;NFIN" {
        return Some(cit.to_string());
    }
    let vowel_final = stem.chars().next_back().is_some_and(|c| VOWELS.contains(c));
    let pres = format!("{stem}{}", if vowel_final { "ydi" } else { "adi" });
    let past = format!("{stem}di");
    let fut = format!("{stem}{}", if vowel_final { "yajak" } else { "ajak" });
    let imp = format!("{stem}sin");
    Some(match feat {
        "V;PRS;3;SG" => pres,
        "V;PRS;3;PL" => format!("{pres}lar"),
        "V;PST;3;SG" => past,
        "V;PST;3;PL" => format!("{past}lar"),
        "V;FUT;3;SG" => fut,
        "V;FUT;3;PL" => format!("{fut}lar"),
        "V;AOR;3;SG" => format!("{stem}ar"),
        "V;AOR;3;PL" => format!("{stem}arlar"),
        "V;IMP;3;SG" => imp,
        "V;IMP;3;PL" => format!("{imp}lar"),
        _ => return None,
    })
}

/// A conjugatable Uzbek verb, cited by its infinitive.
#[derive(Debug, Clone)]
pub struct Verb {
    citation: String,
    overrides: HashMap<&'static str, &'static str>,
}

impl Verb {
    /// Build a verb from its infinitive (-moq).
    pub fn from_infinitive(citation: &str) -> Result<Self, Error> {
        let lowered = citation.trim().to_lowercase();
        let cit = if overrides(citation.trim()).is_none() && overrides(&lowered).is_some() {
            lowered.clone()
        } else {
            citation.trim().to_string()
        };
        if cit.is_empty() || cit.contains(char::is_whitespace) {
            return Err(Error::NotAVerb);
        }
        if !cit.ends_with("moq") && overrides(&cit).is_none() {
            return Err(Error::NotAVerb);
        }
        let over = overrides(&cit).unwrap_or_default();
        Ok(Self {
            citation: cit,
            overrides: over,
        })
    }

    /// The infinitive (citation).
    pub fn citation(&self) -> &str {
        &self.citation
    }

    /// The form for a feature bundle: a mined override if one exists, else
    /// the productive suffix rule.
    pub fn form(&self, feature: &str) -> Option<String> {
        if let Some(f) = self.overrides.get(feature) {
            return Some((*f).to_string());
        }
        productive(&self.citation, feature)
    }
}

/// A compact conjugation table — the third-person synthetic core, shared
/// by the WebAssembly and Python bindings.
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct Table {
    /// Infinitive (the citation).
    pub infinitive: String,
    /// Present 3sg / 3pl.
    pub present: Vec<Option<String>>,
    /// Past definite 3sg / 3pl.
    pub past: Vec<Option<String>>,
    /// Future definite 3sg / 3pl.
    pub future: Vec<Option<String>>,
    /// Aorist 3sg / 3pl.
    pub aorist: Vec<Option<String>>,
    /// Imperative 3sg / 3pl.
    pub imperative: Vec<Option<String>>,
}

impl Table {
    #[must_use]
    pub fn build(v: &Verb) -> Self {
        let many = |feats: &[&str]| feats.iter().map(|f| v.form(f)).collect();
        Self {
            infinitive: v.citation().to_string(),
            present: many(&["V;PRS;3;SG", "V;PRS;3;PL"]),
            past: many(&["V;PST;3;SG", "V;PST;3;PL"]),
            future: many(&["V;FUT;3;SG", "V;FUT;3;PL"]),
            aorist: many(&["V;AOR;3;SG", "V;AOR;3;PL"]),
            imperative: many(&["V;IMP;3;SG", "V;IMP;3;PL"]),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(cit: &str) -> Verb {
        Verb::from_infinitive(cit).unwrap()
    }

    #[test]
    fn consonant_and_vowel_stems() {
        let s = v("sikmoq"); // consonant stem sik-
        assert_eq!(s.form("V;PRS;3;SG").unwrap(), "sikadi");
        assert_eq!(s.form("V;PST;3;SG").unwrap(), "sikdi");
        assert_eq!(s.form("V;IMP;3;SG").unwrap(), "siksin");
        let i = v("ishlamoq"); // vowel stem ishla-
        assert_eq!(i.form("V;PRS;3;SG").unwrap(), "ishlaydi");
        assert_eq!(i.form("V;PRS;3;PL").unwrap(), "ishlaydilar");
        assert_eq!(i.form("V;FUT;3;SG").unwrap(), "ishlayajak");
        assert_eq!(i.form("V;NFIN").unwrap(), "ishlamoq");
    }
}
